### ISSUE TITLE
compile-smoke: native promise .then() broken in microtask-02..07 + edge-promises (regressed by #1000 or #1004)

### ISSUE THREAD

**Issue by proggeramlug** [PerryTS/perry#1008]
## Symptom

The `compile-smoke` job's `Native no-fallback gate` step is failing on
every PR rebased onto current main. The failure is `TypeError: then is
not a function` at runtime for 7 of the curated native-only fixtures:

```
FAIL edge-promises:                    TypeError: then is not a function
FAIL microtask-07-promise-all-mixed:   TypeError: then is not a function
FAIL microtask-02:                     TypeError: then is not a function
FAIL microtask-03:                     TypeError: then is not a function
FAIL microtask-04:                     TypeError: then is not a function
FAIL microtask-05:                     TypeError: then is not a function
FAIL microtask-06:                     TypeError: then is not a function
PASS microtask-01
native-no-fallback-tests: 28 passed, 7 failed
```

Driver: `scripts/run_native_no_fallback_tests.sh`.

## Bisect

Confirmed green on `9f9f78be` (PR #997 merge) and red by `409aeade` /
`ecf11c73`. The only two commits in between are:

- `409aeade` — fix(jsruntime): Effect.pipe(map) chain composition (#1000)
- `ecf11c73` — fix(jsruntime): jose JWT (HS256) end-to-end (#1004)

Both #1000 and #1004 merged with `compile-smoke: FAILURE` already on
their CI, so the regression was visible at merge time and got bypassed
or overlooked.

#1000's commit message specifically mentions changes that could
plausibly affect native dispatch:

> 1. HIR `js_transform`: extend the closure -> `JsCreateCallback`
>    rewrite to `StaticMethodCall` args when the class name is a
>    JS-imported value (mirrors the existing `JsCallMethod` /
>    `JsCallFunction` arms).

If the "JS-imported value" detection is too permissive (e.g. matches
the native `Promise` global), then `Promise.resolve().then(...)` would
get rewritten through `JsCreateCallback` and hit V8's "then is not a
function" instead of native promise dispatch.

## Suspect fixture

`microtask-01` (which passes) doesn't use `.then()` at all — it relies
on `await`. Every failing fixture either calls `.then()` directly or
goes through `Promise.all()` / `edge-promises` shapes. Pure-`await`
microtask FIFO ordering works; `.then()` dispatch is what broke.

## Repro

```bash
cargo build --release -p perry-runtime -p perry-stdlib -p perry
./target/release/perry test-files/test_microtask_inv_02_then_vs_await_fifo.ts -o /tmp/p
/tmp/p
```

### Expected (node --experimental-strip-types parity)

```
sync
then1
then2
B
```

### Actual

```
TypeError: then is not a function
```

(exit 1)

## Why this matters now

This is the third stale-on-main blocker today after #958 (cargo-test
crypto rejection) and #1003 (api-docs-drift). With `compile-smoke` red
on main, every subsequent PR inherits the failure — #944, #947, #958,
#1000, #1003, #1004 all needed admin-bypass.

## Acceptance

- [ ] `microtask-02`..`microtask-07` and `edge-promises` exit 0 with
      output matching `node --experimental-strip-types`.
- [ ] `Promise.resolve().then(fn)` does not dispatch through V8 in
      pure-TS code (the no-fallback gate stays green).
- [ ] No regression on `microtask-01` (the await-only path), Effect.pipe(map)
      (the case #1000 was fixing), or jose JWT (the case #1004 was fixing).

## Likely fix shape

Narrow the #1000 `js_transform` predicate that rewrites
`StaticMethodCall` closure args to `JsCreateCallback`. The rewrite
should fire only when the receiver class is genuinely a JS-imported
module export, not for any class accessible as a static-method receiver
— in particular not for the native `Promise` global.
