### ISSUE TITLE
Runtime `require()` of a `.node` path never reaches the Node-API loader: computed addon paths (node-gyp-build, bindings, node-pty) fail with "Cannot find module", even when the file is in the sidecar

### ISSUE THREAD

**Issue by proggeramlug** [PerryTS/perry#10457]
Found by the package audit (compiling real npm packages from source instead of Perry's native bindings) on
Perry e6dcb6274d (v0.5.1587), Linux x64. Only a `.node` specifier that is a string literal in a CommonJS `require` is lowered to the authenticated loader. Any `require()` that runs at runtime with a `.node` path throws `Cannot find module` without consulting the sidecar manifest. Also, when an approved package loads its addon only through a computed path, the compiler writes no sidecar and gives no diagnostic.

## Reproduction
Needs a C compiler and Node's headers, which ship in the Node tarball under `include/node`. No npm packages.

`addon.c`
```c
#include <node_api.h>

static napi_value Hello(napi_env env, napi_callback_info info) {
  napi_value out;
  napi_create_string_utf8(env, "world", NAPI_AUTO_LENGTH, &out);
  return out;
}

NAPI_MODULE_INIT() {
  napi_value fn;
  napi_create_function(env, "hello", NAPI_AUTO_LENGTH, Hello, NULL, &fn);
  napi_set_named_property(env, exports, "hello", fn);
  return exports;
}
```
`package.json`
```json
{
  "name": "computed-addon-path",
  "private": true,
  "type": "module",
  "dependencies": { "demo-addon": "1.0.0" },
  "perry": {
    "compilePackages": ["demo-addon"],
    "nativeAddons": ["demo-addon"],
    "allow": { "compilePackages": ["*"] }
  }
}
```
`node_modules/demo-addon/package.json`
```json
{ "name": "demo-addon", "version": "1.0.0", "main": "index.js" }
```
`node_modules/demo-addon/index.js`
```js
const path = require("path");
// node-gyp-build / bindings / node-pty shape: the .node path is computed at runtime.
module.exports = require(path.join(__dirname, "build", "Release", "addon.node"));
```
`main.ts`
```ts
import addon from "demo-addon";
console.log(addon.hello());
```
```sh
mkdir -p node_modules/demo-addon/build/Release
cc -shared -fPIC -I"$(dirname "$(dirname "$(command -v node)")")/include/node" addon.c \
   -o node_modules/demo-addon/build/Release/addon.node
node main.ts
PERRY_NO_AUTO_OPTIMIZE=1 perry compile main.ts -o app && ./app
```
**Variant 2: the file IS in the sidecar.** Add this line to `index.js` above `module.exports`. The line never runs; it only creates a static graph edge:
```js
if (process.env.DEMO_STATIC_EDGE) require("./build/Release/addon.node");
```
**Variant 3: a project file loaded through `createRequire` with a literal path.** Use `"perry": { "nativeAddonPaths": ["native/addon.node"] }` and copy the addon to `native/addon.node`:
```ts
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const addon = require("./native/addon.node");
console.log(addon.hello());
```

## Expected (Node 26.5.1)
All three variants print:
```
world
```

## Actual (Perry)
Variant 1: compile succeeds with **no `app.perry-native` directory and no warning**, then:
```
Error: Cannot find module '<dir>/node_modules/demo-addon/build/Release/addon.node'
    at new __AnonShape_dee4f7c0327dd60c (<anonymous>)
```
Variant 2: the sidecar is written and its manifest contains `demo-addon/build/Release/addon.node -> 607b5f658c7484d0/build/Release/addon.node`, but the run fails the same way:
```
Error: Cannot find module '<dir>/node_modules/demo-addon/build/Release/addon.node'
    at new __AnonShape_dee4f7c0327dd60c (<anonymous>)
```
Variant 3: the sidecar is written and contains `$project/native/addon.node -> 9f71c07a493f697f/addon.node`, then:
```
Error [MODULE_NOT_FOUND]: Cannot find module '<dir>/native/addon.node'
    at <anonymous>
```
The results are the same with `PERRY_NO_AUTO_OPTIMIZE=1` and with the default auto-optimize build.

## Impact
Every mainstream addon loader computes the path, so none of these packages can load its real addon through `perry.nativeAddons`:
- **bcrypt 6.0.0** (`bcrypt.js:2` → `require('node-gyp-build')(path.resolve(__dirname))`) and **argon2 0.45.1** (`argon2.cjs:4-6`). The loader is node-gyp-build 4.8.4, `node-gyp-build.js:21-22`: `function load (dir) { return runtimeRequire(load.resolve(dir)) }`, where `load.resolve` returns `<dir>/prebuilds/<platform>-<arch>/<name>.<tags>.node`. The audit pinned bcrypt's prebuild with a static `require` so it was in the sidecar (variant 2). Perry still printed `Error: Cannot find module '<dir>/node_modules/bcrypt/prebuilds/linux-x64/bcrypt.glibc.node'` in auto mode. In no-auto mode the pin itself first fails with #10458.
- **better-sqlite3 13.0.2**, default entry: `lib/binding.js` → `require(filename)` with `filename = path.join(__dirname, '..', 'prebuilds', `${target}.node`)`. Only the `better-sqlite3/<platform>` subpath entries use a literal require.
- **node-pty 1.1.0** `lib/utils.js:17-29` (`require(dir + "/" + name + ".node")`): `Error: Failed to load native module: pty.node, checked: build/Release, build/Debug, prebuilds/linux-x64: Error: Cannot find module './prebuilds/linux-x64//pty.node'`.
- **@lydell/node-pty 1.1.0** `requireBinary.js:3-7` (`require("@lydell/node-pty-" + process.platform + "-" + process.arch + "/" + file)`): `The @lydell/node-pty package supports your platform (linux-x64), but it could not find the binary package for it: @lydell/node-pty-linux-x64/pty.node`.
- **@parcel/watcher 2.5.1** `index.js:3-15` (`require(name)` with a computed platform package name). It is also blocked by a deliberate exclusion, described below.

## Notes
- **Runtime half.** `require_thunk` → `require_path` (`crates/perry-runtime/src/module_require.rs:686-706`, `:529-653`) has no `.node` arm. An unregistered path falls through to `throw_module_not_found` at `module_require.rs:617-619`. The authenticated loader is reached only through `process.dlopen`, and a literal `.node` require in a CommonJS file is rewritten into `process.dlopen(nativeModule, "<package>/<relative>")` at `crates/perry/src/commands/compile/cjs_wrap/wrap.rs:440-447`. Meanwhile `manifest_entry_for` (`crates/perry-runtime/src/node_api_host/loader.rs:141-173`) already maps an absolute `…/node_modules/<pkg>/<rel>` request or a unique suffix match to a manifest entry. The documented contract, `docs/src/internals/node-api-host.md:370-375` ("Runtime-computed paths may load only a file present in the compile-time addon manifest") and `:19-20` ("`require()` and `process.dlopen()` share that authorization and cache"), is not implemented for `require`. Suggested direction (inferred): route a resolved `.node` request in `require_path` and `resolve_request` to `node_api_host::load_addon` when the host feature is linked. Keep the manifest as the authorization boundary so an unlisted file still fails.
- **Compile half.** With only computed edges, `collect_node_addon_request` (`crates/perry/src/commands/compile/collect_modules/native_addon.rs:163-243`) is never called, so `ctx.native_addons` stays empty. The result is no sidecar, no host feature, and a clean compile. For a package that is explicitly listed in `perry.nativeAddons`, the compiler could stage its target-matching `*.node` payload without a static edge, or at least warn that the package's addon was never reached. #9606's acceptance criteria ask that "dynamic, non-provable paths remain rejected with a diagnostic explaining how to declare the addon"; here no diagnostic appears.
- **Deliberate exclusion to remove along with the Rust @parcel/watcher facade.** `package_is_parcel_watcher_facade` (`native_addon.rs:261-264`) makes every `.node` under `@parcel/watcher` or `@parcel/watcher-*` invisible to the host, at `native_addon.rs:196-202` (`collect_node_addon_request` returns `Ok(None)`), `:251-257` (`collect_or_refuse_node_addon` reports the file as handled), `:354-355` and `:410-412`. Verified: with `"nativeAddons": ["@parcel/watcher", "@parcel/watcher-linux-x64-glibc"]` and a static `require("@parcel/watcher-linux-x64-glibc/watcher.node")`, compilation succeeds with no sidecar and no diagnostic, and `typeof binding.subscribe` is `undefined` (Node: `function`). Adding `@parcel/watcher` to `compilePackages` leads to the package's own `No prebuild or local build of @parcel/watcher found` error.
- A literal require from a project CommonJS file reaches the loader but with the wrong logical id; see #10462. Related: #9606 (`import.meta.require` discovery), #8523.
