### PR TITLE
fix(runtime): honor JSON reviver prototype lookups

### LINKED ISSUE #4656: Object [[Get]] does not inherit user-assigned Object.prototype properties through the prototype chain
Surfaced while landing #4595 (JSON.parse reviver). General object-model gap, **not** reviver-specific.

A plain object's `[[Get]]` does not walk to `Object.prototype` for properties assigned there at runtime. Minimal repro:

```ts
(Object.prototype as any).foo = 99;
const o: any = { foo: 1 };
delete o.foo;
console.log(o.foo); // Node: 99 (inherited)   Perry: 1 / undefined
```

Node prints `99`; Perry returns the stale own value (or `undefined` after delete) — the inherited `Object.prototype.foo` is never consulted.

Failing test262 (`built-ins/JSON/parse/`), which rely on re-reading an inherited value after the reviver deletes the own property:
- `reviver-object-get-prop-from-prototype`
- `reviver-array-get-prop-from-prototype`

The reviver walk now correctly does a real `[[Get]]` re-read per #4595; it's `[[Get]]`'s prototype-chain traversal for assigned `Object.prototype` members that's missing.

### LINKED ISSUE #4657: Array integer-index [[DefineOwnProperty]]/accessor descriptors not honored (Object.defineProperty on array indices)
Surfaced while landing #4595 (JSON.parse reviver). General array-model gap, **not** reviver-specific.

`Object.defineProperty(arr, '<index>', desc)` on an array does not record the index's descriptor in the property-attrs/accessor tables the way object properties do, so:
- `{configurable:false}` on an index isn't seen by later `CreateDataProperty`/`[[Delete]]` (they overwrite/remove the slot anyway).
- A `{get}` accessor installed on an index isn't invoked by `[[Get]]`.

Minimal repro:
```ts
const a = [1, 2];
Object.defineProperty(a, '1', { configurable: false });
Object.defineProperty(a, '1', { value: 99 }); // Node: throws / no-op keeping 2
console.log(a[1]); // Node: 2    Perry: 99
```

Failing test262 (`built-ins/JSON/parse/`):
- `reviver-array-non-configurable-prop-create`, `reviver-array-non-configurable-prop-delete` (object equivalents already pass as of #4595)
- `reviver-get-name-err` (throwing getter installed on an array index must fire during the reviver's `[[Get]]`)

Related: array integer-indexed exotic `[[DefineOwnProperty]]` work for typed arrays in #4353/#4357 — this is the ordinary-Array index-descriptor slice.

### PR DESCRIPTION
**Pull request by andrewtdiz**
## Summary
- Re-read JSON reviver holder properties through object and array prototype fallback after revivers delete own properties.
- Preserve the original array receiver when inherited accessors are invoked during those fallback reads.
- Honor numeric array accessor descriptors and configurable/enumerable attrs in define/get/delete/descriptor paths used by reviver internalization.
- Extend the Node parity fixture for object/array prototype rereads, inherited accessor receivers, nonconfigurable array indices, and getter abrupt completion.

Closes #4656.
Closes #4657.

## Batching rationale
Both gaps are exercised by the same `JSON.parse` reviver internalization flow: the runtime deletes or defines holder properties and then immediately re-reads them. Splitting object prototype fallback from array numeric descriptor handling would leave the fixture only partially aligned.

## Tests
- `npm exec --yes --package=node@26 -- node --experimental-strip-types test-parity/node-suite/globals/json-parse-reviver-internalize.ts`
- `cargo test -p perry-runtime json -j 2`
- `cargo test -p perry-runtime array -j 2`
- `cargo test -p perry-runtime object -j 2 -- --test-threads=1`
- `cargo check -p perry-runtime -j 2`
- `cargo fmt --all -- --check`
- `git diff --check HEAD~1..HEAD`
- `./scripts/check_file_size.sh`

Focused parity command attempted locally with `CARGO_BUILD_JOBS=1 PERRY_NO_AUTO_OPTIMIZE=1`, but the release build did not complete on this machine: earlier attempts were killed by signal 9 while unrelated release parity builds were active, and a later wrapper exited before producing a report while new unrelated http2 release builds had restarted. No focused parity mismatch report was produced.

## Non-goals
This is scoped to reviver-relevant prototype fallback and numeric array descriptor behavior; it is not a full rewrite of array exotic descriptor invariants.

### CODE REVIEW

**Comment by proggeramlug** [comment]
## Status: needs a deeper fix — converting back to draft

I rebased this onto current `main`, resolved the conflicts (`object/array_object_ops.rs` + `object/descriptors.rs` — `main` had independently grown a *more complete* `define_array_property` / `getOwnPropertyDescriptor` accessor path, so I kept main's, which also fixed the original stack overflow in `test_array_exotic_descriptors_and_global_prototype_identity`), and verified the feature works (`json-parse-reviver-internalize.ts` passes: getters fire during internalize, abrupt getters throw, non-configurable delete/define respected). Array + object unit tests (59 + 27) pass locally.

**But CI surfaced a second, deeper stack overflow** that I traced to a design hazard in the hot-path approach:

### Root cause: address-reuse stale-descriptor hazard
This PR adds accessor-descriptor consultation to the two hottest read paths — `js_object_get_field_by_name` (array-index branch) and `js_array_get_f64` — gated by the global `descriptors_in_use()` / thread-local `ACCESSORS_IN_USE` flags. The accessor side table (`ACCESSOR_DESCRIPTORS`) is keyed by **object address** (`usize`).

Once any object defines an accessor, the global gate stays on for the rest of the process. When an object that held a descriptor is freed and its address is **reused** by a new object, a read of the new object finds the **stale** `(addr, key)` entry and invokes the dead getter with the new object as `this` — which re-enters the same read path → unbounded recursion.

Reproduces deterministically in `cargo test -p perry-runtime --test-threads=1` (overflow lands in `node_stream::state_tests::stream_object_mode_flags_default_false_and_follow_options`, but only *after* enough earlier descriptor-defining tests have run to populate + reuse addresses — running that test in isolation, or with just the array-exotic test, passes). `main` doesn't hit this because it only consults the table in cold reflection paths (`getOwnPropertyDescriptor`/`defineProperty`), where the object is guaranteed live.

### What the fix needs
- Either **clear** `ACCESSOR_DESCRIPTORS` / `PROPERTY_DESCRIPTORS` entries when an object is freed (a GC sweep hook keyed on the freed address), **or** gate the hot-path consultation on a **per-ObjectHeader/ArrayHeader flag** (`has_accessor_descriptors`) set at define-time — so a reused address (fresh header, flag clear) never consults stale entries. The per-header flag is cheaper but still leaks across same-key reuse, so the GC-sweep approach is the robust one.
- Also: `ordinary_object_prototype_property_value` here drops the `is_primitive_proto_method` gate so *every* missing-property read now falls through to an `Object.prototype[key]` lookup with receiver rebinding — worth confirming that's intended (perf + the broadened fallback widen the recursion surface).

The conflict-resolved branch is pushed (it builds and the feature works); it just shouldn't land until the lifecycle hazard above is closed. Happy to pair on the GC-sweep hook. Thanks @andrewtdiz.

**Comment by proggeramlug** [comment]
**Additional root-cause dimension — the side table is unsafe under Perry's *moving* GC.**

Beyond the free/address-reuse hazard above: Perry's generational GC evacuates non-pinned tenured objects to old-gen with full reference rewriting (C4b policy). `ACCESSOR_DESCRIPTORS` / `PROPERTY_DESCRIPTORS` are keyed by raw object **address** in a runtime `HashMap` — which the GC's pointer-rewriting does **not** touch. So when an object that owns a descriptor is moved:
- the descriptor entry still points at the **old** address → the object silently **loses** its accessor, and
- the old address (now free / reused) keeps a **stale** entry → the same dead-getter-fires hazard.

So a correct fix can't just prune on sweep — the descriptor tables need to be **GC-relocation-aware** (rekeyed when an object moves, dropped when it dies), or the per-object descriptor state needs to live in a slot the GC already rewrites/clears (not the address-keyed HashMap, and not the codegen-ABI-coupled `ObjectHeader`; `GcHeader._reserved` is partly used for layout state).

`main` keeps this latent because it only consults the table in cold reflection paths (`getOwnPropertyDescriptor`/`defineProperty`) on objects that are provably live and un-moved for the duration of the call. Moving the consult onto the hot `js_object_get_field_by_name` / `js_array_get_f64` paths (this PR) is what exposes both the reuse and the relocation hazards. Recommend designing the descriptor storage to be GC-coordinated before re-landing.

**Comment by proggeramlug** [comment]
Rebased onto current `main` and got CI-green locally. Summary of what was blocking and what changed:

- **`lint` (file-size)** — the >2000-line `intrinsics.rs` flagged on the old base is allowlisted on current `main`; `check_file_size.sh` passes after rebase.
- **`cargo-test` (stack overflow in `node_stream::state_tests`)** — no longer reproduces on current `main`.
- **`error[E0425]`** — the rename `ordinary_object_prototype_method_value` → `…_property_value` missed a new-on-main call site in `ordinary_has_property`; updated it (the `in`/HasProperty path now also honors user-assigned `Object.prototype` members, consistent with this PR's intent).
- Dropped the stale `v0.5.1141` release commit (maintainer bumps version + CHANGELOG at merge per repo convention).

Validation:
- `cargo test -p perry-runtime --lib` under `TZ=UTC`: green. The only failures seen are pre-existing flakes that all pass in isolation (`stream_constructors_expose_static_method_values`, two global-prototype-identity array tests sharing global ctor init) plus the TZ-sensitive `test_full_year_setters_revive_invalid_date_only` (passes under `TZ=UTC`/CI).
- End-to-end parity: `test-parity/node-suite/globals/json-parse-reviver-internalize.ts` compiled with Perry is **byte-identical** to `node --experimental-strip-types`.

Closes #4656, Closes #4657.

**Comment by proggeramlug** [comment]
Added commit `cfebd4ea3` — fixes the `cargo-test` failure at its root.

**Root cause:** `GLOBAL_THIS_PTR` is a process-global static, but the realm global it points at lives in a *per-thread* arena. libtest runs each test on its own thread, so a global published by a finished test thread was read by later threads as a stale pointer into freed/reused memory — `globalThis.Array`/`Object` came back `undefined`, which drove both the array-intrinsics test failure and the `node_stream` recursion→stack-overflow. This PR's reviver paths just allocate enough to push the reused slot into corruption, which is why it surfaced here.

**Fix (2 files, runtime + test):**
- `object/global_this.rs`: `js_get_global_this` validates the cached pointer (`is_valid_obj_ptr` + `obj_type == GC_TYPE_OBJECT`) and re-creates a fresh per-thread global when stale. In production the global is never freed, so it validates true on the fast path and never thrashes — only the genuinely-stale cross-thread case re-creates. (Also hardens worker-thread `globalThis` access in `perry/thread`.)
- `array/tests.rs`: hardened `test_array_exotic_descriptors_and_global_prototype_identity` to resolve its whole intrinsic snapshot inside one retry iteration (re-reading every key), robust to GC moving the raw pointers it holds.

**Validation:**
- `RUST_TEST_THREADS=1 cargo test -p perry-runtime` (CI's exact config): **997 passed, 0 failed**, 5 consecutive runs, no overflow/SIGBUS.
- Reviver parity fixture (`json-parse-reviver-internalize.ts`): still **byte-identical** to `node --experimental-strip-types`.
- Release multi-threaded: only the pre-existing `stream_constructors_expose_static_method_values` parallel flake (passes in isolation), unrelated to this change.

**Comment by proggeramlug** [comment]
Revised the global fix to be safer (force-pushed `0ef2efe9d`):

- The first version *validated* the cached `GLOBAL_THIS_PTR` by dereferencing it — but that pointer can come from another thread's freed arena, and dereferencing it to read the GC header is itself unsafe on platforms that unmap freed pages (this showed up as an intermittent `set.rs` SIGSEGV on the Linux runner).
- New approach: `js_get_global_this` caches the global in a **thread-local** and only ever returns a global *this* thread created — it never dereferences a foreign pointer. It still publishes to the `GLOBAL_THIS_PTR` GC-root slot so the running thread's collector marks the live global. Single-threaded production is unchanged.
- Also fixed the `lint` (rustfmt) miss.

Local validation: `RUST_TEST_THREADS=1 cargo test -p perry-runtime` (CI's exact config) — **997 passed, 0 failed, 4 consecutive runs.**

**Comment by proggeramlug** [comment]
## Handoff for Linux debugging — set.rs:121 SIGSEGV

Everything below `cargo-test` is green; the one blocker is a **Linux-only SIGSEGV** I can't reproduce on macOS.

### Exact repro (CI's config)
```
RUST_TEST_THREADS=1 CARGO_PROFILE_TEST_DEBUG=0 cargo test -p perry-runtime
```
Fails deterministically (4/4 CI runs) in `array::tests::test_array_splice_delete_middle` (a pure-numeric splice test) at **`set.rs:121`** — the `(*header).obj_type` deref inside `is_registered_set`, with a non-unwinding abort (SIGSEGV → SIGABRT). macOS: 8+ runs at 997/0.

### What's established
- The reviver's node_stream **stack overflow masked everything past it**; once the global fix removes the overflow, the suite reaches this splice test and aborts.
- `is_registered_set(addr)` dereferences `addr - 8` for any `addr >= 0x100000` *before* the `SET_REGISTRY` lookup (deliberate perf path). A stale/garbage address that's unmapped on Linux faults there; mimalloc on macOS retains freed pages, so it doesn't.
- `main` passes this step reliably (no retry on it), so this is **introduced** by the changes here, not a pre-existing flake — most likely a raw pointer left **stale by GC moving/reclaiming** an object now that scanners are registered and full marking/evacuation runs in the test harness.

### Suggested next steps on Linux
1. `RUST_BACKTRACE=1` + run under `gdb`/`rr` to capture the **caller** of `is_registered_set` and the offending `addr` (is it a numeric f64 bit-pattern, a moved/evacuated object, or a freed one?).
2. Toggle `PERRY_GEN_GC_EVACUATE=0` and `PERRY_WRITE_BARRIERS=0` on that command to see if disabling evacuation/barriers clears it (would confirm a move-then-stale-raw-pointer).
3. If confirmed: either guard the `is_registered_set`/`is_registered_map` deref (registry-first / arena-bounds) or fix the caller (`array/flat_clone.rs:88`, `array/from_concat.rs:428`) to not pass a stale/non-pointer address.

### Branch state (`c890e260e`)
- `object/global_this.rs`: per-thread `globalThis` (no cross-thread deref) + `ensure_gc_initialized` so the global is born under a live root.
- `gc/mod.rs`: idempotent per-thread `ensure_gc_initialized` + suppress flag.
- `gc/tests/support.rs`: `ScopedRootScannerRegistryGuard` suppresses auto-init + save/restores the registry (keeps the GC tests' controlled roots).
- `array/tests.rs`: hardened the intrinsic-identity test.

Local CI-gate: 997/0 ×7; parity fixture byte-identical to Node.

**Comment by proggeramlug** [comment]
Pushed `816ba6d82` — a targeted fix for the Linux `set.rs:121` SIGSEGV at its source.

`is_registered_set`/`is_registered_map` dereferenced the GC header (`addr - 8`) *before* the registry lookup, guarded only by `addr < 0x100000`. That doesn't catch a stale/garbage address *above* the floor, so an unmapped one faults on Linux (mimalloc retains freed pages on macOS → never reproduced here). Now both check the registry (keyed by address, pruned on free) first and only deref a *registered* address. Cost: the documented ~5.7%-samples header pre-filter — happy to revert that and instead guard differently if you'd prefer to keep the fast path.

Local CI-gate (`RUST_TEST_THREADS=1 cargo test -p perry-runtime`): 997/0 ×2. I can't reproduce the Linux fault on macOS, so this CI run is the real test — if `cargo-test` goes green, #4665 should be mergeable.

**Comment by proggeramlug** [comment]
Replaced the registry-first patch with the **root-cause** fix (`c2675d28a`).

The `set.rs`/`indexing.rs` SIGSEGVs were two symptoms of one thing: perry-runtime unit tests hold GC-managed pointers as raw locals on the **native (Rust) stack**, and the conservative scan **skips the native stack by default** (deliberate — compiled code roots via the shadow stack). So any collection triggered mid-test reclaims those locals, and the next GC-header deref reads freed memory — an intermittent SIGSEGV on Linux (freed pages unmapped; mimalloc retains them on macOS, hiding it). This is exactly the 'GC/threading tests race into intermittent SIGSEGV' your cargo-test job already documents (test.yml:190); #4665's reviver allocations make it fire reliably. Guarding individual deref sites is whack-a-mole (the SIGSEGV just moved set.rs → indexing.rs).

Fix: `conservative_stack_scan_mode` defaults to **`Full`** under `#[cfg(test)]` (production unchanged) so test locals survive any mid-test GC. The GC tests, which verify collection of objects held only as native-stack locals, opt back to `Auto` via a per-thread override — `ScopedRootScannerRegistryGuard` covers the guarded majority, `ConservativeScanAutoGuard` the one ad-hoc oldgen defrag test.

This makes the runtime test suite robust to mid-test GC permanently, not just for this PR. Local CI-gate (`RUST_TEST_THREADS=1`): **997/0 ×4**. This CI run is the real verdict on Linux.
