### ISSUE TITLE
regression: 'class X extends EventTarget' throws 'EventTarget is not a function' (re-breaks #6301, unnoticed because parity is tag-gated)

### ISSUE THREAD

**Issue by proggeramlug** [PerryTS/perry#7518]
## Symptom

`class Sub extends EventTarget` throws at construction:

```
TypeError: EventTarget is not a function
    at <anonymous>
```

`test-files/test_gap_6301_event_target_subclass.ts` prints its first five lines
(the *plain* `new EventTarget()` surface, which still works), then dies. Perry
exits **1**, node exits **0**.

```
$ node --experimental-strip-types test-files/test_gap_6301_event_target_subclass.ts   # 12 lines, exit 0
$ perry test-files/test_gap_6301_event_target_subclass.ts -o /tmp/et && /tmp/et       # 5 lines, exit 1
```

## This is a regression of a closed issue

#6301 was fixed and closed on **2026-07-13** by #6311 ("EventTarget methods must
live on the prototype so subclasses inherit them"), which added this test. The
test passed at that commit. It now fails, so the fix — or something it depended
on — has been undone.

Reproduced on **two independent hosts** (the dev Mac and the pinned quiet mini),
at v0.5.1292/v0.5.1293, deterministically. It is **not** in
`test-parity/gap_snapshot.json` or `test-parity/known_failures.json`, i.e.
nothing recorded it as an accepted failure — it is simply unnoticed.

## Why nobody saw it

`parity` (which runs the gap suite) is **gated to tag pushes only** — see
CLAUDE.md, "Workflow Requirements". So a gap regression can land on `main` and
sit indefinitely: no per-PR run fails, and the tag-time run is far from the
commit that caused it.

That makes the blast radius wider than this one test. I found two more
non-snapshot gap failures in the same sweep, previously misfiled (by me) as
host-local flakes on the strength of their reproducing on clean `main`:
`test_gap_diagchannel_3082_3084_3085_3086` and
`test_gap_crypto_cipher_3382_3381_2954` (plus `test_gap_zlib_4917_level`, a link
failure). "Fails on clean `main`" was taken as evidence of a host quirk when it
was in fact evidence of an *older, equally unnoticed* regression. Each needs the
same treatment.

## Likely area

The native-base-subclass family is a documented weak area (CLAUDE.md,
"Known-weak areas"): a native base's surface is installed at `super()` time and
its parent edge lives in the class registry, and keying any of that on a
**literal `extends` name** loses it for fieldless classes, indirect subclasses
and class expressions. `EventTarget is not a function` reads like the
constructor lookup — not the method inheritance #6311 fixed — so check whether
the binding for the native ctor is being resolved at all in the subclass path.

## Acceptance

`test_gap_6301_event_target_subclass` byte-identical to node with exit 0, plus a
bisect naming the commit that broke it, so the same class of regression can be
recognized next time.

**Comment by proggeramlug** [comment]
Bisected and fixed in #7520.

## First bad commit: `c6ed8175d` — "fix(globals): complete Node parity" (#6853, 2026-07-30)

Predicate: compile and run `class Bus extends EventTarget {}; new Bus()`, own
`--profile perry-dev` build of
`-p perry -p perry-runtime -p perry-stdlib -p perry-runtime-static -p perry-stdlib-static`
at every point, object cache cleared between points.

| commit | | verdict |
|---|---|---|
| `81ab8e5d6` | #6311, the commit that fixed #6301 and added the test | **GOOD** |
| `17c0ff952` | `c6ed8175d^` | **GOOD** |
| `c6ed8175d` | #6853 | **BAD** |
| `33acba4c1` | `main` | **BAD** |

## What shape of change did it

A **one-line data-table edit**, and a correct one: `"EventTarget"` was added to
`builtin_constructor_spec_length` so `EventTarget.length` reads `0` like Node.
The damage happened three files away.

`try_dispatch_value_called_proto_method`
(`crates/perry-runtime/src/object/native_call_method/proto_dispatch.rs`) serves the
#3716 uncurry-this idiom: a built-in *prototype method* invoked as a value arrives
backed by the shared `global_this_builtin_noop_thunk`, so the helper recovers the
closure's recorded `name` and re-dispatches `IMPLICIT_THIS.<name>(…)` by name.
Global *constructors* share that thunk. The only thing keeping them out was an
accident, stated in the helper's own doc comment:

> Gated on a recorded built-in `.length` so bare no-op-backed global constructors
> (`const O = SomeCtor; O()`), which **never call `set_builtin_closure_length`**,
> are excluded.

`populate_global_this_builtins` calls `set_builtin_closure_length` for every name
`builtin_constructor_spec_length` answers. So the exclusion was never an invariant
— it was an incomplete table — and completing the table opened the gate.

The rest follows: `class Bus extends EventTarget {}` has no static parent class
id, so `super()` runs the parent VALUE through `js_fetch_or_value_super`, which
binds `IMPLICIT_THIS` to the new instance before the value call. That became
`bus.EventTarget()`, and the by-name tower's catch-all threw.

Your "likely area" note was right that the constructor lookup, not the method
inheritance, was failing — though the resolution itself was fine; it was the
*call* of the resolved value that got re-routed.

**The recognizable pattern for next time**: a change that makes a metadata table
more complete, where some other module's behaviour depends on that table being
*incomplete*. Nothing in the diff of #6853 looks dangerous, and nothing in
`proto_dispatch.rs` changed. #7520 converts the implicit coupling into an explicit
predicate plus a `cargo-test`-tier assertion over the whole table, so growing
`builtin_constructor_spec_length` again cannot re-open it for a different name.

The same hole was already open for every other no-op-thunk-backed global
constructor carrying a spec `.length` (`AbortController`, `AbortSignal`,
`FormData`, `TextEncoder`, `DisposableStack`, `URLSearchParams`, …) — `EventTarget`
is just the one with a gap test. And the `Function | GeneratorFunction |
AsyncGeneratorFunction` special case sitting in the same function (#5588) is an
earlier instance of the identical bug, patched name-by-name.

## The three siblings

Re-measured on the same host, same `perry-dev` arm. All three PASS at `c6ed8175d`
(2026-07-30), so all three broke later — none is host-local. But only one still
reproduces under `perry-dev` at `main`:

| test | `c6ed8175d` | `main` | filed |
|---|---|---|---|
| `test_gap_diagchannel_3082_3084_3085_3086` | PASS | **FAIL** | #7521 |
| `test_gap_crypto_cipher_3382_3381_2954` | PASS | PASS | #7523 |
| `test_gap_zlib_4917_level` | PASS | PASS | #7522 |

None is explained by this root cause. The two that do not reproduce were observed
under the **release**-profile harness, so they are profile-dependent rather than
host-local — for the zlib link failure that is a strong lead, since an undefined
symbol that is present in the archive is a dead-strip symptom and `perry-dev` has
no LTO (`KEEP_ZLIB_FFI` in `perry-stdlib/src/zlib.rs` exists for exactly that
failure mode). Details and the re-check recipe are in each issue.
