### ISSUE TITLE
test262 language/class tail — 197 fails (async-gen static methods, accessor-name computed-in, private brand)

### ISSUE THREAD

**Issue by proggeramlug** [PerryTS/perry#5592]
**Current state — 197 failing.** _Snapshot from the 2026-06-29 full sweep (perry 0.5.1208, node v26.3.0). Supersedes the original body; the complete current failing-test list is inline below — no re-run needed to start._

Class tail: async-generator static methods (`yield*` delegation — note the `yield-star-sync-next` regression from #5751), computed accessor names with `in`, private-field brand checks, missed negatives. See breakdown below.

## Failure reasons
| n | reason |
|---|---|
| 29 | Uncaught exception: Expected a TypeError to be thrown but no exception |
| 12 | SyntaxError: new.target expression is not allowed here |
| 9 | Uncaught exception: Expected SameValue(«undefined», «1») to be true |
| 8 | Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.itera |
| 7 | TypeError: value is not a function |
| 6 | Uncaught exception: invalid access of c1 private method Expected a Typ |
| 5 | Uncaught exception: Expected a ReferenceError to be thrown but no exce |
| 5 | TypeError: GeneratorFunction is not a function |
| 4 | TypeError: Cannot access private member from an object whose class did |
| 4 | Uncaught exception: Expected SameValue(«1», «1») to be false |
| 4 | TypeError: Cannot read properties of undefined (reading 'access') |
| 4 | Uncaught exception: Expected SameValue(«false», «true») to be true |

## By area
**statements** 140 · **expressions** 57

## All 197 failing tests (path — reason)
<details><summary>full list — click to expand</summary>

```
language/expressions/class/async-gen-method-static/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/expressions/class/async-gen-method/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/expressions/class/class-name-ident-await-escaped.js    Error: Failed to parse <staged-case> Parse error: E
language/expressions/class/class-name-ident-await.js    Error: Failed to parse <staged-case> Parse error: E
language/expressions/class/constructor-this-tdz-during-initializers.js    Uncaught exception: Expected a ReferenceError to be thrown but no exception was thrown at 
language/expressions/class/elements/arrow-body-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/expressions/class/elements/arrow-body-private-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/expressions/class/elements/async-gen-private-method-static/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/expressions/class/elements/async-gen-private-method/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/expressions/class/elements/class-name-static-initializer-expr.js    Uncaught exception: Expected SameValue(«"expr"», «"C"») to be true
language/expressions/class/elements/direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/expressions/class/elements/fields-computed-name-static-propname-prototype.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/expressions/class/elements/fields-multiple-definitions-static-private-methods-proxy.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/expressions/class/elements/fields-run-once-on-double-super.js    Uncaught exception: Expected a ReferenceError to be thrown but no exception was thrown at 
language/expressions/class/elements/indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/expressions/class/elements/intercalated-static-non-static-computed-fields.js    Uncaught exception: 0 should be an own property
language/expressions/class/elements/nested-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/expressions/class/elements/nested-indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/expressions/class/elements/nested-private-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/expressions/class/elements/nested-private-indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/expressions/class/elements/private-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/expressions/class/elements/private-indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/expressions/class/elements/private-method-get-and-call.js    TypeError: #m is not a function
language/expressions/class/elements/private-static-field-usage-inside-nested-class.js    Uncaught exception: accessed static private field from an arbritary object Expected a Type
language/expressions/class/elements/prod-private-getter-before-super-return-in-field-initializer.js    Uncaught exception: private getters are not installed before super returns Expected a Type
language/expressions/class/elements/prod-private-method-before-super-return-in-field-initializer.js    Uncaught exception: private methods are not installed before super returns Expected a Type
language/expressions/class/elements/prod-private-setter-before-super-return-in-field-initializer.js    Uncaught exception: private setters are not installed before super returns Expected a Type
language/expressions/class/elements/static-field-declaration.js    Uncaught exception: h should be an own property
language/expressions/class/elements/static-private-fields-proxy-default-handler-throws.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/expressions/class/elements/static-private-method-referenced-from-instance-method.js    TypeError: Cannot access private member from an object whose class did not declare it
language/expressions/class/elements/static-private-methods-proxy-default-handler-throws.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/expressions/class/elements/super-access-from-arrow-func-on-field.js    TypeError: Cannot assign to read only property 'staticProp' of object '#<Object>'
language/expressions/class/elements/syntax/valid/grammar-static-ctor-accessor-meth-valid.js    Uncaught exception: Expected SameValue(«1», «1») to be false
language/expressions/class/elements/syntax/valid/grammar-static-ctor-async-gen-meth-valid.js    Error: Failed to parse <staged-case> Parse error: E
language/expressions/class/elements/syntax/valid/grammar-static-ctor-async-meth-valid.js    Error: Failed to parse <staged-case> Parse error: E
language/expressions/class/elements/syntax/valid/grammar-static-ctor-gen-meth-valid.js    Uncaught exception: Expected SameValue(«1», «1») to be false
language/expressions/class/elements/syntax/valid/grammar-static-ctor-meth-valid.js    Parse warning: Error { error: (7773..7779, TS1089("static")) }
language/expressions/class/name.js    Uncaught exception: name descriptor value should be ; name value should be
language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-eval-indirect.js    TypeError: undefined is not a constructor
language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-factory.js    Uncaught exception: invalid access of c1 private method Expected a TypeError to be thrown 
language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-eval-indirect.js    TypeError: undefined is not a constructor
language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-factory.js    Uncaught exception: invalid access of c1 private method Expected a TypeError to be thrown 
language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-eval-indirect.js    TypeError: undefined is not a constructor
language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-factory.js    Uncaught exception: invalid access of c1 private method Expected a TypeError to be thrown 
language/expressions/class/private-static-field-multiple-evaluations-of-class-eval-indirect.js    TypeError: Cannot read properties of undefined (reading 'access')
language/expressions/class/private-static-field-multiple-evaluations-of-class-factory.js    TypeError: Cannot access private member from an object whose class did not declare it
language/expressions/class/private-static-getter-multiple-evaluations-of-class-eval-indirect.js    TypeError: Cannot read properties of undefined (reading 'access')
language/expressions/class/private-static-getter-multiple-evaluations-of-class-factory.js    Uncaught exception: invalid access of C1 private static getter Expected a TypeError to be 
language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-eval-indirect.js    TypeError: Cannot read properties of undefined (reading 'access')
language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-factory.js    Uncaught exception: invalid access of c1 private static method Expected a TypeError to be 
language/expressions/class/private-static-setter-multiple-evaluations-of-class-eval-indirect.js    TypeError: Cannot read properties of undefined (reading 'access')
language/expressions/class/private-static-setter-multiple-evaluations-of-class-factory.js    Uncaught exception: invalid access of C1 private static setter Expected a TypeError to be 
language/expressions/class/restricted-properties.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/expressions/class/scope-name-lex-open-heritage.js    Uncaught exception: inner binding rejects modification Expected a TypeError to be thrown b
language/expressions/class/scope-name-lex-open-no-heritage.js    Uncaught exception: inner binding rejects modification Expected a TypeError to be thrown b
language/expressions/class/setter-length-dflt.js    Uncaught exception: length descriptor value should be 0; length value should be 0
language/expressions/class/subclass-builtins/subclass-SharedArrayBuffer.js    Uncaught exception: Expected true but got false
language/statements/class/arguments/access.js    Uncaught exception: The value of `Subclass.length` is `0`, because there are 0 formal para
language/statements/class/arguments/default-constructor.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/async-gen-method-static/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/statements/class/async-gen-method/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/statements/class/classelementname-abrupt-completion.js    Uncaught exception: Expected a Test262Error to be thrown but no exception was thrown at al
language/statements/class/definition/constructable-but-no-prototype.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/definition/constructor-strict-by-default.js    Uncaught exception: Expected a ReferenceError to be thrown but no exception was thrown at 
language/statements/class/definition/fn-name-accessor-get.js    TypeError: Cannot read properties of undefined (reading 'get')
language/statements/class/definition/fn-name-accessor-set.js    TypeError: Cannot read properties of undefined (reading 'set')
language/statements/class/definition/fn-name-gen-method.js    TypeError: Cannot convert undefined or null to object
language/statements/class/definition/fn-name-method.js    TypeError: Cannot convert undefined or null to object
language/statements/class/definition/numeric-property-names.js    TypeError: value is not a function
language/statements/class/definition/prototype-getter.js    Uncaught exception: The value of `calls` is `1` Expected SameValue(«0», «1») to be true
language/statements/class/definition/prototype-setter.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/definition/this-access-restriction-2.js    Uncaught exception: The result of `exn instanceof ReferenceError` is `true` Expected SameV
language/statements/class/definition/this-access-restriction.js    Uncaught exception: Expected a ReferenceError to be thrown but no exception was thrown at 
language/statements/class/definition/this-check-ordering.js    Uncaught exception: The result of `exn instanceof ReferenceError` is `true` Expected SameV
language/statements/class/elements/arrow-body-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/statements/class/elements/arrow-body-private-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/statements/class/elements/async-gen-private-method-static/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/statements/class/elements/async-gen-private-method/yield-star-sync-next.js    Test262:AsyncTestFailure:Test262Error: Test262Error: get [Symbol.iterator] thisValue Expec
language/statements/class/elements/class-field-is-observable-by-proxy.js    Uncaught exception: Expected SameValue(«0», «3») to be true
language/statements/class/elements/computed-property-abrupt-completition.js    Uncaught exception: computed property should have abrupt completion Expected a Test262Erro
language/statements/class/elements/direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/statements/class/elements/fields-computed-name-static-computed-var-propname-constructor.js    Uncaught exception: constructor should be an own property
language/statements/class/elements/fields-computed-name-static-computed-var-propname-prototype.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/fields-computed-name-static-propname-constructor.js    Uncaught exception: constructor should be an own property
language/statements/class/elements/fields-computed-name-static-propname-prototype.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/fields-hash-constructor-is-a-valid-name.js    Uncaught exception: #constructor should be an own property
language/statements/class/elements/indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/statements/class/elements/intercalated-static-non-static-computed-fields.js    Uncaught exception: 0 should be an own property
language/statements/class/elements/nested-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/statements/class/elements/nested-indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/statements/class/elements/nested-private-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/statements/class/elements/nested-private-indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/statements/class/elements/private-accessor-is-visible-in-computed-properties.js    Uncaught exception: access to a private acessor from ordinary object Expected a TypeError 
language/statements/class/elements/private-direct-eval-err-contains-newtarget.js    SyntaxError: new.target expression is not allowed here
language/statements/class/elements/private-field-is-not-clobbered-by-computed-property.js    Uncaught exception: Expected SameValue(«false», «true») to be true
language/statements/class/elements/private-field-is-visible-in-computed-properties.js    Uncaught exception: access to a not defined private field in object should throw a TypeErr
language/statements/class/elements/private-field-with-initialized-id-is-visible-in-computed-properties.js    Uncaught exception: access to a not defined private field in object should throw a TypeErr
language/statements/class/elements/private-getter-brand-check-multiple-evaluations-of-class.js    Uncaught exception: invalid access of c1 private method Expected a TypeError to be thrown 
language/statements/class/elements/private-getter-is-not-clobbered-by-computed-property.js    Uncaught exception: Expected SameValue(«false», «true») to be true
language/statements/class/elements/private-indirect-eval-contains-arguments.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/statements/class/elements/private-method-brand-check-multiple-evaluations-of-class.js    Uncaught exception: invalid access of c1 private method Expected a TypeError to be thrown 
language/statements/class/elements/private-method-brand-check-super-class.js    Uncaught exception: Expected SameValue(«"test262"», «"super class"») to be true
language/statements/class/elements/private-method-comparison-multiple-evaluations-of-class.js    Uncaught exception: Expected SameValue(«function () { [native code] }», «function () { [na
language/statements/class/elements/private-method-double-initialisation-get-and-set.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/private-method-double-initialisation-get.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/private-method-double-initialisation-set.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/private-method-double-initialisation.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/private-method-get-and-call.js    TypeError: #m is not a function
language/statements/class/elements/private-method-is-not-clobbered-by-computed-property.js    Uncaught exception: Expected SameValue(«false», «true») to be true
language/statements/class/elements/private-method-is-visible-in-computed-properties.js    Uncaught exception: access to a private method from ordinary object Expected a TypeError t
language/statements/class/elements/private-setter-brand-check-multiple-evaluations-of-class.js    Uncaught exception: invalid access of c1 private method Expected a TypeError to be thrown 
language/statements/class/elements/private-setter-is-not-clobbered-by-computed-property.js    Uncaught exception: Expected SameValue(«false», «true») to be true
language/statements/class/elements/private-static-field-usage-inside-nested-class.js    Uncaught exception: accessed static private field from an arbritary object Expected a Type
language/statements/class/elements/privatefield-on-proxy.js    Error compiling module 'case.js' (<staged-case> wit
language/statements/class/elements/privatefieldadd-typeerror.js    Error compiling module 'case.js' (<staged-case> wit
language/statements/class/elements/privatefieldget-typeerror-1.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/privatefieldget-typeerror-4.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/privatefieldset-evaluation-order-3.js    TypeError: Cannot access private member from an object whose class did not declare it
language/statements/class/elements/privatefieldset-typeerror-1.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/privatefieldset-typeerror-10.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/privatefieldset-typeerror-11.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/privatefieldset-typeerror-4.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/privategetter-on-proxy.js    (no output)
language/statements/class/elements/privatemethods-on-proxy.js    (no output)
language/statements/class/elements/prod-private-getter-before-super-return-in-field-initializer.js    Uncaught exception: private getters are not installed before super returns Expected a Type
language/statements/class/elements/prod-private-method-before-super-return-in-field-initializer.js    Uncaught exception: private methods are not installed before super returns Expected a Type
language/statements/class/elements/prod-private-setter-before-super-return-in-field-initializer.js    Uncaught exception: private setters are not installed before super returns Expected a Type
language/statements/class/elements/public-class-field-initialization-is-visible-to-proxy.js    Uncaught exception: Expected a Test262Error to be thrown but no exception was thrown at al
language/statements/class/elements/public-class-field-initialization-on-super-class-with-setter.js    Uncaught exception: Test262Error:
language/statements/class/elements/static-field-declaration.js    Uncaught exception: h should be an own property
language/statements/class/elements/static-private-fields-proxy-default-handler-throws.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/elements/static-private-method-referenced-from-instance-method.js    TypeError: Cannot access private member from an object whose class did not declare it
language/statements/class/elements/super-access-from-arrow-func-on-field.js    TypeError: Cannot assign to read only property 'staticProp' of object '#<Object>'
language/statements/class/elements/syntax/valid/grammar-static-ctor-accessor-meth-valid.js    Uncaught exception: Expected SameValue(«1», «1») to be false
language/statements/class/elements/syntax/valid/grammar-static-ctor-async-gen-meth-valid.js    Error: Failed to parse <staged-case> Parse error: E
language/statements/class/elements/syntax/valid/grammar-static-ctor-async-meth-valid.js    Error: Failed to parse <staged-case> Parse error: E
language/statements/class/elements/syntax/valid/grammar-static-ctor-gen-meth-valid.js    Uncaught exception: Expected SameValue(«1», «1») to be false
language/statements/class/elements/syntax/valid/grammar-static-ctor-meth-valid.js    Parse warning: Error { error: (7768..7774, TS1089("static")) }
language/statements/class/name-binding/const.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/name-binding/in-extends-expression-assigned.js    Generating code...
language/statements/class/name-binding/in-extends-expression-grouped.js    Generating code...
language/statements/class/name-binding/in-extends-expression.js    Generating code...
language/statements/class/params-dflt-gen-meth-static-ref-arguments.js    Uncaught exception: first parameter Expected SameValue(«undefined», «"third"») to be true
language/statements/class/params-dflt-meth-static-ref-arguments.js    Uncaught exception: first parameter Expected SameValue(«undefined», «"third"») to be true
language/statements/class/poisoned-underscore-proto.js    Uncaught exception: Expected SameValue(«0», «1») to be true
language/statements/class/restricted-properties.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/scope-name-lex-close.js    Uncaught exception: Expected SameValue(«1», «null») to be true
language/statements/class/scope-name-lex-open-heritage.js    Uncaught exception: Expected SameValue(«1», «null») to be true
language/statements/class/scope-name-lex-open-no-heritage.js    Uncaught exception: Expected SameValue(«1», «null») to be true
language/statements/class/setter-length-dflt.js    Uncaught exception: length descriptor value should be 0; length value should be 0
language/statements/class/static-classelementname-abrupt-completion.js    Uncaught exception: Expected a Test262Error to be thrown but no exception was thrown at al
language/statements/class/static-init-abrupt.js    Uncaught exception: subsequent field Expected SameValue(«true», «false») to be true
language/statements/class/static-init-arguments-methods.js    ReferenceError: arguments is not defined
language/statements/class/static-init-scope-var-close.js    Uncaught exception: Expected SameValue(«"first block"», «"outer scope"») to be true
language/statements/class/static-init-sequence.js    Uncaught exception: Expected SameValue(«"second field"», «"first block"») to be true
language/statements/class/static-init-super-property.js    Uncaught exception: Expected SameValue(«undefined», «"test262"») to be true
language/statements/class/strict-mode/arguments-callee.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/subclass-builtins/subclass-SharedArrayBuffer.js    Uncaught exception: Expected true but got false
language/statements/class/subclass/binding.js    Uncaught exception: The value of `s2.x` is `1` Expected SameValue(«8», «1») to be true
language/statements/class/subclass/builtin-objects/Array/contructor-calls-super-multiple-arguments.js    Uncaught exception: Actual [, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , 
language/statements/class/subclass/builtin-objects/Array/length.js    Uncaught exception: Expected SameValue(«undefined», «"foo"») to be true
language/statements/class/subclass/builtin-objects/Array/regular-subclassing.js    Uncaught exception: Expected SameValue(«0», «2») to be true
language/statements/class/subclass/builtin-objects/ArrayBuffer/regular-subclassing.js    TypeError: value is not a function
language/statements/class/subclass/builtin-objects/Boolean/regular-subclassing.js    Uncaught exception: Expected SameValue(«[object Object]», «true») to be true
language/statements/class/subclass/builtin-objects/DataView/regular-subclassing.js    Uncaught exception: Expected SameValue(«undefined», «») to be true
language/statements/class/subclass/builtin-objects/Date/regular-subclassing.js    Uncaught exception: Expected SameValue(«NaN», «1859») to be true
language/statements/class/subclass/builtin-objects/Function/instance-length.js    Uncaught exception: length should be an own property
language/statements/class/subclass/builtin-objects/Function/instance-name.js    Uncaught exception: name should be an own property
language/statements/class/subclass/builtin-objects/Function/regular-subclassing.js    TypeError: value is not a function
language/statements/class/subclass/builtin-objects/GeneratorFunction/instance-length.js    TypeError: GeneratorFunction is not a function
language/statements/class/subclass/builtin-objects/GeneratorFunction/instance-name.js    TypeError: GeneratorFunction is not a function
language/statements/class/subclass/builtin-objects/GeneratorFunction/instance-prototype.js    TypeError: GeneratorFunction is not a function
language/statements/class/subclass/builtin-objects/GeneratorFunction/regular-subclassing.js    TypeError: GeneratorFunction is not a function
language/statements/class/subclass/builtin-objects/GeneratorFunction/super-must-be-called.js    TypeError: GeneratorFunction is not a function
language/statements/class/subclass/builtin-objects/Map/regular-subclassing.js    Uncaught exception: Expected SameValue(«undefined», «1») to be true
language/statements/class/subclass/builtin-objects/Number/regular-subclassing.js    Uncaught exception: Expected SameValue(«"NaN"», «"42.00"») to be true
language/statements/class/subclass/builtin-objects/Object/constructor-returns-non-object.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/subclass/builtin-objects/Promise/regular-subclassing.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/subclass/builtin-objects/Proxy/no-prototype-throws.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/subclass/builtin-objects/RegExp/lastIndex.js    TypeError: value is not a function
language/statements/class/subclass/builtin-objects/RegExp/regular-subclassing.js    TypeError: value is not a function
language/statements/class/subclass/builtin-objects/Set/regular-subclassing.js    Uncaught exception: Expected SameValue(«undefined», «2») to be true
language/statements/class/subclass/builtin-objects/String/length.js    Uncaught exception: length should be an own property
language/statements/class/subclass/builtin-objects/String/regular-subclassing.js    Uncaught exception: Expected SameValue(«"[object Object]"», «"test262"») to be true
language/statements/class/subclass/builtin-objects/Symbol/new-symbol-with-super-throws.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/subclass/builtin-objects/TypedArray/regular-subclassing.js    Uncaught exception: Expected SameValue(«0», «2») to be true (Testing with Float64Array and
language/statements/class/subclass/builtin-objects/TypedArray/super-must-be-called.js    TypeError: Constructor %TypedArray% requires 'new'
language/statements/class/subclass/builtin-objects/WeakMap/regular-subclassing.js    TypeError: value is not a function
language/statements/class/subclass/builtin-objects/WeakSet/regular-subclassing.js    TypeError: value is not a function
language/statements/class/subclass/builtins.js    Uncaught exception: The value of `eua.length` is `10` Expected SameValue(«0», «10») to be 
language/statements/class/subclass/class-definition-null-proto-missing-return-override.js    Uncaught exception: Expected a ReferenceError to be thrown but no exception was thrown at 
language/statements/class/subclass/class-definition-null-proto-super.js    Uncaught exception: Expected a TypeError to be thrown but no exception was thrown at all
language/statements/class/subclass/class-definition-null-proto.js    Uncaught exception: Expected SameValue(«[object Object]», «null») to be true
language/statements/class/subclass/default-constructor-2.js    Uncaught exception: The value of `s2prime.x` is `3` Expected SameValue(«undefined», «3») t
language/statements/class/super/in-constructor-superproperty-evaluation.js    Uncaught exception: `super[super()]` via `new Derived()` throws a ReferenceError Expected 
language/statements/class/super/in-constructor.js    Uncaught exception: The value of `super.x` is `42` Expected SameValue(«undefined», «42») t
language/statements/class/syntax/class-expression-binding-identifier-opt-class-element-list.js    Uncaught exception: Expected SameValue(«"function"», «"undefined"») to be true
```
</details>

## Reproduce
```
scripts/test262_subset.py --root vendor/test262 --dir language/statements/class language/expressions/class --jobs 6
```
Each path is under `vendor/test262/test/`; assemble harness + case per `test-compat/test262/README.md` to run one under `perry compile`.

**Comment by proggeramlug** [comment]
Update 2026-06-24: #5599 landed (yield* final IteratorValue) — class tail **260 → 240**.

**Comment by proggeramlug** [comment]
Note (re-measure 2026-06-25): the raw class-tail count rose 240 → 257, but that is **inflated by the new #5657 regression** (23 `class extends <builtin>` subclass-builtins cases). Excluding those, the genuine class tail is ~234. Triage #5657 first.

**Comment by proggeramlug** [comment]
Note (re-measure 2026-06-26): raw class-tail count is now 295, but **inflated by a new regression** — ~61 `language/expressions/class` static-method default-param/destructuring cases (filed separately, root #5662). True class tail ≈ 234. Triage that regression first.

**Comment by proggeramlug** [comment]
Re-measure 2026-06-27: class tail **295 → 230** — the #5703 regression recovered, now below the pre-regression ~234. True standing gap.

**Comment by proggeramlug** [comment]
Cloud worker → **PR #5751** (code-only, +325/-14, fmt clean). Fixed the single largest class-tail root: **async-generator `yield*` delegation** — `yield-star-*` dirs **40 → 16 (−24)**, 0 regressions. Landed: non-object `next()` result → TypeError, `gen.return(v)` forwarding to the delegated iterator, and `%AsyncFromSyncIteratorPrototype%.{return,throw}` GetMethod-once semantics. Remaining 16 (`*-throw`) need the async-generator dispatch-loop continuation (#4374). Same root as **#5745** (this lands the `.return()` half) and unblocks part of **#5591**’s AsyncFromSyncIterator cluster.

**Comment by proggeramlug** [comment]
Superseded by self-contained per-area worklist tickets — each has the complete current failing-test list inline (2026-07-01 sweep), so an agent can open one and work immediately (no history, no re-measure):

#5832 language/class · #5833 language-misc · #5834 built-ins-misc · #5835 intl-small · #5836 RegExp · #5837 NumberFormat · #5838 Array · #5839 Temporal · #5840 DateTimeFormat · #5841 eval-code · #5842 Object · #5843 String · #5844 Proxy · #5845 intl402-misc · #5846 Function · #5847 JSON · #5848 annexB-misc · #5849 Promise.
