### ISSUE TITLE
Node API compatibility epic: node:os and node:tty host constants, stdio stream, and validation parity

### ISSUE THREAD

**Issue by andrewtdiz** [PerryTS/perry#3826]
## Summary

`node:os` and `node:tty` are claimed by Perry and have broad curated smoke coverage, but current upstream Node samples still expose host/terminal API behavior gaps. This epic groups the host-environment and terminal/stdio surfaces that remain after the older closed parity cuts, with explicit links to adjacent issues where the root cause belongs elsewhere.

## Evidence

Baseline:
- Perry `origin/main@ffebfca51c97500a93074a4338241fc5e44b4fff` (`fix(node:fs): add disposable mkdtemp and path error parity (#3814)`)
- Node sparse checkout `nodejs/node v22.x@7b1b943` (`Working on v22.22.4`)
- Release build: `cargo build --release -p perry -p perry-runtime -p perry-stdlib`

Claimed API surface from `target/release/perry --print-api-manifest`:

```text
os   24 entries -> EOL, arch, availableParallelism, constants, cpus, default, devNull, endianness, freemem, getPriority, homedir, hostname, loadavg, machine, networkInterfaces, platform, release, setPriority, tmpdir, totalmem, type, uptime, userInfo, version
tty  20 entries -> ReadStream, WriteStream, _refreshSize, addListener, clearLine, clearScreenDown, cursorTo, getColorDepth, getWindowSize, hasColors, isatty, moveCursor, off, on, once, removeAllListeners, removeListener, setRawMode
```

Focused upstream radar command:

```sh
scripts/node_core_subset.py \
  --root /tmp/perry-nodejs \
  --api os tty \
  --max-per-api 50 \
  --sample-cap 50 \
  --perry-bin /Users/dutchess/Documents/PerryTS/perry/target/release/perry \
  --report /tmp/perry-node-core-small-builtins.json
```

Relevant result from the combined run:

```text
os  pass=0 diff=0 rt-fail=6 compile-fail=0 node-skip=2 parity=0%
tty pass=1 diff=0 rt-fail=1 compile-fail=0 node-skip=1 parity=50%
```

Upstream runtime-failure samples:

```text
os/test-os-constants-signals.js              TypeError: value is not a function
os/test-os-eol.js                            Missing expected exception
os/test-os-homedir-no-envvar.js              Expected values to be strictly equal
os/test-os-process-priority.js               thrown error did not match expected matcher
os/test-os-userinfo-handles-getter-errors.js (no output)
os/test-os.js                                expression evaluated to a falsy value
tty/test-tty-stdin-pipe.js                   TypeError: input.on is not a function
```

Node-skipped under the shim, so not charged to Perry yet:

```text
os/test-os-checked-function.js
os/test-os-fast.js
tty/test-tty-backwards-api.js
```

Curated suite cross-checks on the same build:

```sh
./run_parity_tests.sh --suite node-suite --module os
```

```text
Parity Pass:  32
Parity Fail:  4
Compile Fail: 3
Output mismatches:
  node-suite/os/constants/errno-selected-extra
  node-suite/os/constants/priority-and-signals
  node-suite/os/imports/default-import
  node-suite/os/properties/eol-and-constants-identity
Compile failures:
  node-suite/os/methods/loadavg
  node-suite/os/platform/loadavg-and-cpus-shape
  node-suite/os/userinfo/invalid-options
```

```sh
./run_parity_tests.sh --suite node-suite --module tty
```

```text
Parity Pass:  26
Parity Fail:  0
Compile Fail: 6
Compile failures:
  node-suite/tty/classes/callable-constructors
  node-suite/tty/classes/has-colors-with-count
  node-suite/tty/classes/invalid-fd-constructors
  node-suite/tty/isatty/object-coercion
  node-suite/tty/isatty/object-values
  node-suite/tty/process/stdio-fd-events
```

Duplicate/adjacent issue check:
- #1271 tracks optional PTY-backed parity tests for interactive tty behavior.
- #3663 covers classic stream objects missing `on`/`write`/`pipe` on some construction paths, which may be the root cause of `test-tty-stdin-pipe.js`.
- #3804 covers broader ESM/default export hygiene, which may include `node-suite/os/imports/default-import`.
- Older `os`/`tty` cuts such as #3317, #3206, #3207, #3208, #3753, and #3599 are closed, so they do not track this current upstream failure set.

## Scope

Close the host/terminal API parity gaps that remain after the basic export/shape cuts:

- `os.constants` nested tables, especially `signals`, `errno`, `priority`, and their namespace/default identities.
- `os.EOL`, `os.homedir()`, `os.tmpdir()`, `os.getPriority()` / `setPriority()`, `os.userInfo()` error handling, and deterministic shape checks for `loadavg()`, `cpus()`, and network interfaces.
- `os` default export identity if the broader default-export fix in #3804 does not resolve it first.
- `tty.ReadStream` / `tty.WriteStream` constructor validation, callable constructor behavior, `isatty()` coercion for objects and edge primitives, `hasColors()` count/options validation, and stdio event method availability.
- `process.stdin` / readline / tty stream integration for the upstream `test-tty-stdin-pipe.js`, coordinating with #3663 and #1271 where the fix or test harness belongs outside `node:tty` itself.

## Acceptance

- Add or update curated upstream-derived fixtures under:
  - `test-parity/node-suite/os`
  - `test-parity/node-suite/tty`
- Existing green curated fixtures remain green.
- These commands pass, with remaining host-dependent values either shape-tested or explicitly skiplisted with reasons:

```sh
./run_parity_tests.sh --suite node-suite --module os
./run_parity_tests.sh --suite node-suite --module tty
```

- A focused upstream radar run no longer shows Perry runtime failures for distilled deterministic `os`/`tty` behavior cases:

```sh
scripts/node_core_subset.py \
  --root vendor/nodejs \
  --api os tty \
  --max-per-api 75 \
  --sample-cap 50 \
  --report /tmp/perry-node-core-os-tty.json
jq '.totals, .per_api, .samples' /tmp/perry-node-core-os-tty.json
```

- Any remaining failures caused by PTY availability, host-specific values, process stdio stream primitives, or ESM default export behavior are linked to the owning issue (#1271, #3663, #3804, or a narrower follow-up) rather than being silently counted as `node:os`/`node:tty` implementation work.

**Comment by proggeramlug** [comment]
Closing this **umbrella/epic tracker** as superseded by granular per-gap tracking.

Perry tracks Node/TypeScript parity gaps as **granular, per-gap issues** — that is the workable backlog the maintainer prefers, rather than umbrella/epic roll-ups that coordinate or re-scope other epics. The concrete leaf gaps remain (or should be filed) as focused issues and are addressed by PRs that auto-close the specific leaf they fix; closing this epic loses no implementation work, only the duplicate coordination framing. If a consolidated tracker for this module/area is still wanted, feel free to reopen.
