### ISSUE TITLE
Tracking: Effect framework end-to-end compat (post-#309 / #310)

### ISSUE THREAD

**Issue by proggeramlug** [PerryTS/perry#321]
## Goal

Get [Effect](https://effect.website/) (`effect@3.21.2` and later) to compile + link + run end-to-end via `perry compile` with `perry.compilePackages: ["effect"]`. This validates Perry on one of the largest pure-TypeScript libraries in the ecosystem (~150 modules, ~30k LOC for `Effect.ts` alone) and proves Perry can handle the heavy-generics / heavy-closures / fiber-runtime patterns that mid-to-large TS apps use.

## Status snapshot (perry 0.5.405)

✅ **Module collection** — 362 modules collected (#310 closed: namespace re-exports traverse correctly)
✅ **Codegen completes** — no OOM, codegen runs to completion (#309 closed: was 34 GB RSS / 7m SIGKILL)
🔴 **Codegen produces 26 module failures** — see sub-issues
🔴 **Link fails** — 901 missing-symbol references resolving to ~5 distinct root causes

## Sub-issues blocking end-to-end

| # | Issue | Modules affected | Severity |
|---|---|---|---|
| #318 | closure-collector dead arms (`use of undefined value '@perry_closure_*'`) | 17 | **largest** — single fix flips many modules |
| #314 | closure-call arity ceiling at 5 args | 5 | high — easy to bump constant if runtime supports it |
| #320 | ReadableStream / Web Streams stdlib not implemented | needed by Stream module | medium — requires new stdlib work |
| #319 | `string self-append: local N not in scope` | 1 | low — likely subsumed by #318 |
| #315 | `String.startsWith` 2-arg form | 1 | low |
| #316 | `String.slice()` 0-arg form | 1 | low |
| #317 | `String.matchAll` codegen | 1 | low |

## Reproducible test bed

```bash
mkdir effect-compat && cd effect-compat
cat > package.json <<'JSON'
{
  "name": "effect-compat",
  "version": "0.0.0",
  "type": "module",
  "perry": { "compilePackages": ["effect"] }
}
JSON
bun add effect
```

```typescript
// test_minimal.ts
import { Effect } from "effect";
const program = Effect.succeed(42);
const result = Effect.runSync(program);
console.log("result:", result);
```

```bash
perry compile test_minimal.ts -o /tmp/out
# Expected eventually: "result: 42"
# Today: link fails (post-#309/#310)
```

## Recommended fix order (by leverage)

1. **#318** — closure-collector walker fix is the biggest win and prevents this bug class from recurring on any future package. Recommend the v0.5.329 Tier 1.1 pattern (centralize via `perry_hir::walker::walk_expr_children`).
2. **#314** — single-line fix if the runtime already supports up to 16 args (it does).
3. **#315 + #316 + #317** — small focused fixes in `lower_string_method.rs`, can land as one PR.
4. **#319** — recheck after #318; likely subsumed.
5. **#320** — biggest scope; can be deferred until everything else is done since Effect's Stream is one of many features users want, but other Effect parts (Effect.gen, Layer, Schedule, etc.) work without it.

## Definition of done

The minimal repro above produces a binary that prints `result: 42` and exits 0. Bonus: `Effect.gen` + `Effect.runPromise` of an async program also works.

## Backlog beyond the link errors

Even after #314-#320 are fixed, two pre-existing categorical gaps will surface in user code that touches Effect deeply:
- **`arguments` magic object** — Effect's `dual()` helper uses it 148 times to implement data-first / data-last API duality. Already documented in `docs/src/language/limitations.md`. Workaround: keep using "unknown identifier 'arguments'" warnings for now; long-term, support `arguments` or land a `dual()` shim.
- **`Intl.*`** — DateTime / Schedule / Duration formatting. Adjacent to existing perry-runtime i18n work.

Cross-references: #309 (OOM, fixed), #310 (silent-zero, fixed).

**Comment by proggeramlug** [comment]
All seven sub-issues called out in the tracking table are now closed:

| # | Issue | Closed in |
|---|---|---|
| #318 | closure-collector dead arms | v0.5.408 |
| #314 | closure-call arity ceiling at 5 args | v0.5.409 |
| #320 | ReadableStream / Web Streams stdlib | v0.5.410 |
| #319 | string self-append: local N not in scope | v0.5.411 |
| #315 | String.startsWith / endsWith 2-arg form | v0.5.414 |
| #317 | String.matchAll codegen | v0.5.415 |
| #316 | String.slice() 0-arg form | v0.5.424 |

The remaining work to close this umbrella is the Definition of Done smoke test — the 4-line `Effect.runSync(Effect.succeed(42))` repro from this issue's body should compile, link, and print `result: 42`. Recommend running that on a fresh checkout of `main` (≥ v0.5.424) and closing once verified.

Backlog notes in the issue body about `arguments` magic object (Effect's `dual()` helper, 148 sites) and `Intl.*` formatting still apply as separate follow-up work for users compiling Effect deeply.

**Comment by proggeramlug** [comment]
## Status update — perry 0.5.424

All 7 original sub-issues (#314–#320) are closed. Re-running the minimal repro on v0.5.424:

| Phase | v0.5.405 | v0.5.424 |
|---|---|---|
| Modules collected | 362 ✅ | 362 ✅ |
| Codegen failures | 26 | **10** |
| Missing-symbol references | 901 | **419** |
| Final state | link fail | **still link fail** |

**Roughly 60% reduction in failure surface**, but the binary still doesn't link. Three new failure modes have surfaced from the residual tail and are filed as new sub-issues:

| # | Issue | Modules affected |
|---|---|---|
| **#336** | `@perry_class_keys_<module>__<ClassName>` collisions on same-named classes in different scopes | 7 (Refinement×3, Class×2, SingleShotGen×2) |
| **#337** | `@__perry_wrap_perry_unknown_func` referenced in IR but never defined | 2 |
| **#338** | Residual closure-collector miss (post-#318) — undefined `@perry_closure_..._SchemaAST_ts__142` | 1 |

Plus #320 (ReadableStream / Web Streams stdlib) is still the largest stdlib gap.

## Updated checklist

- [x] #309 — 34 GB OOM (codegen) — **closed v0.5.403**
- [x] #310 — silent-zero on namespace re-export — **closed v0.5.405**
- [x] #314 — closure-call arity ceiling at 5 args — closed
- [x] #315 — String.startsWith 2-arg form — closed
- [x] #316 — String.slice() 0-arg form — closed (v0.5.424)
- [x] #317 — String.matchAll codegen — closed
- [x] #318 — closure-collector dead arms (initial sweep) — closed (residual: #338)
- [x] #319 — string self-append local OOS — closed
- [x] #320 — ReadableStream / Web Streams stdlib — open
- [x] #336 — class-keys symbol-name collisions — **new**
- [x] #337 — `__perry_wrap_perry_unknown_func` undefined — **new**
- [x] #338 — residual closure-collector miss on SchemaAST.ts — **new**

End-to-end definition of done (binary prints `result: 42` and exits 0) requires #336 + #337 + #338 + #320.

**Comment by proggeramlug** [comment]
Status update post-v0.5.464:

The smaller sub-issues called out in this umbrella are all closed (#314, #315, #316, #317, #318, #319, #320 — all per the changelog). However, the end-to-end `Effect.runSync(Effect.succeed(42))` repro from this issue's "definition of done" still fails at link with **248 unresolved `@perry_closure_*` symbol references** across multiple Effect modules.

This is the same closure-collector walker bug class that #318 closed — but for closure shapes the v0.5.408 fix didn't yet enumerate. Each new shape needs another pass through `collectors.rs::collect_closures_in_expr`'s walker delegation or a new `Expr` variant added to the centralized walker.

Leaving this open as the umbrella tracking issue. The hot-fix pattern is: rerun the Effect compile, find the closure ID symbol mentioned in the linker error, find its source HIR site, identify which `Expr` variant the codegen-emit path is descending through but the collector isn't, fix the walker.

**Comment by proggeramlug** [comment]
Re-tested perry 0.5.495 against Effect 3.21.2 (same minimal repro from this issue). Two new sub-issues blocking the link:

- #431 — perry-codegen: cross-module class-name collision emits method bodies under the wrong module prefix (sibling of #336, hits 8 Effect modules: `Inspectable.ts`, `Streamable.ts`, `internal/queue.ts`, `internal/fiberId.ts`, `ParseResult.ts`, `Schema.ts`, `SchemaAST.ts`, plus the secondary one named `Class` collisions). Has a 2-file minimal repro.
- #432 — perry-codegen: `@js_array_create` referenced without `declare` in `fiberRuntime.ts` IR. Independent of #431.

Status snapshot at v0.5.495:
- ✅ Module collection, parsing, HIR-lowering: clean across all 177 source files.
- ❌ Codegen: 8 modules fail clang -c — all symptoms collapse to #431 + #432.
- ❌ Link: cascading "undefined symbol" cleanup from those 8 missing `.o`s.
- (Pre-existing) `arguments` warnings still fire ~60×; tracked separately as a known limitation.

Once #431 and #432 land, expect the same minimal repro (`Effect.runSync(Effect.succeed("hi"))`) to be the next thing to test end-to-end. If it links, the next likely runtime layer (generators / `Effect.gen` / `yield*` delegation) hasn't been exercised yet.

**Comment by proggeramlug** [comment]
## Status check on perry 0.5.511 — not yet closeable

All seven listed sub-issues (#314, #315, #316, #317, #318, #319, #320) are now closed. Re-ran the Definition-of-Done repro (`Effect.runSync(Effect.succeed(42))`) on perry 0.5.511. Compile succeeds; **link still fails** with 21 distinct missing-symbol categories.

Two new sub-issues filed to cover the residuals:

- **#460** — `export { local as keyword }` re-exports don't emit definitions for contextual-keyword names (`void`, `async`, `await`, `try`, `delete`, `continue`). Accounts for ~14 of the 21 misses. Effect uses this idiom 8+ times across its tree.
- **#461** — investigation bucket for the remaining ~7: bare `_pull` (closure-capture-mangling regression on nested-arrow locals) + class-as-function references for `Union` / `Emit` / `Order` (mangling routes class names through `_perry_fn_` instead of the class registry).

Recommend keeping #321 open until both #460 and #461 are closed and the repro produces `result: 42` end-to-end. #460 is the leverage fix — clearing those will likely also expose whether the #461 symbols are real bugs or just downstream noise.

**Comment by proggeramlug** [comment]
## Status update — perry 0.5.696

Re-ran the Definition-of-Done repro (`Effect.runSync(Effect.succeed(42))`) on perry 0.5.696. Big leap from the v0.5.511 snapshot:

| Phase | v0.5.405 | v0.5.424 | v0.5.511 | v0.5.696 |
|---|---|---|---|---|
| Modules collected | 362 ✅ | 362 ✅ | 362 ✅ | 362 ✅ |
| Codegen failures | 26 | 10 | (n/a) | **1** |
| Missing-symbol references | 901 | 419 | ~248 | **3** |
| Final state | link fail | link fail | link fail | **link fail** |

All 3 missing symbols collapse to a **single failed module** — `effect/src/Cron.ts` — whose object file isn't emitted, so `_node_modules_effect_src_Cron_ts__init` + `_perry_fn_..._isCron` + `_perry_fn_..._parse` all dangle. The link-side cascade is downstream of one codegen verifier error:

```
clang -c failed (status=exit status: 1)
.../perry_llvm_*_*.ll:3558:59: error: use of undefined value '%r32'
```

The offending function in Cron.ts:846-848:

```ts
function aliasOrValue(field: string, aliases?: Record<string, number>): number {
  return aliases?.[field.toLocaleLowerCase()] ?? Number(field)
}
```

Standalone 2-line repro produces the **identical** `use of undefined value '%r32'` LLVM verifier error:

```ts
function aliasOrValue(field: string, aliases?: Record<string, number>): number {
  return aliases?.[field.toLocaleLowerCase()] ?? Number(field);
}
console.log(aliasOrValue("hello"));               // expected NaN
console.log(aliasOrValue("hello", { hello: 5 })); // expected 5
console.log(aliasOrValue("42"));                  // expected 42
```

The combination of optional chaining (`aliases?.`) + computed-key property access (`[field.toLocaleLowerCase()]`) + nullish coalescing (`?? Number(field)`) on an optional `Record<string, number>` parameter trips perry-codegen — the inline `iget.sym/iget.str/iget.num` dispatch is emitted but the receiver SSA temp it depends on (`%r32`) is never defined in any predecessor block. Looks adjacent to but distinct from #388 (different shape: this one has the computed-key inside the optional chain).

Filing as a new codegen sub-issue; once it lands the DoD repro should produce `result: 42` end-to-end (no other failures in the rest of the build). #321 stays open until then.

**Comment by proggeramlug** [comment]
## Followup — perry 0.5.698

#592 (the `aliasOrValue` codegen bug, root cause = `toLocaleLowerCase`/`toLocaleUpperCase` missing from the string-method dispatcher) landed in 04da56a0. Re-ran the DoD repro on v0.5.698:

| Phase | v0.5.405 | v0.5.424 | v0.5.511 | v0.5.696 | v0.5.698 |
|---|---|---|---|---|---|
| Modules collected | 362 ✅ | 362 ✅ | 362 ✅ | 362 ✅ | 362 ✅ |
| Codegen failures | 26 | 10 | (n/a) | 1 | **0 ✅** |
| Missing-symbol references | 901 | 419 | ~248 | 3 | **0 ✅** |
| Link | fail | fail | fail | fail | **clean ✅** |
| Final state | link fail | link fail | link fail | link fail | **runtime SIGSEGV** |

So compile + link are now clean for the entire Effect tree. The DoD repro builds a 49.2 MB binary that **segfaults at runtime before any output** — even reduced to:

```ts
import { Effect } from "effect";
console.log("imported");
```

…the binary exits 139 with no stdout. The crash is during Effect's module-init (runs before main), so it's neither the `Effect.succeed` nor `Effect.runSync` call — just the importing-and-initializing of Effect's ~150 modules trips something in the runtime layer.

Likely candidates to investigate (haven't bisected yet):
- A startup-time class-table / vtable registration ordering issue
- A QuickJS bridge crash (the build pulled in `libperry_jsruntime.a` because part of Effect's tree wasn't natively-compileable; see the duplicate-symbol warnings for `_js_handle_array_length` / `_js_handle_array_get` between perry-jsruntime and perry-runtime — possibly load-bearing)
- Module-init eval-order on a pure-TS package this large (5 modules / 30k LOC of `Effect.ts` compiled to a single .o)

Will file as a fresh sub-issue under #321 once I have a useful bisection or stack trace. The compile + link gate is officially crossed for the Effect end-to-end story — what remains is one-or-more runtime-layer bugs.

**Comment by proggeramlug** [comment]
## v0.5.706 update + new sub-issue

Re-ran the DoD repro on v0.5.706 (after #592 closed the codegen + link gate). Compile + link **stay clean** — no regression from v0.5.698. The runtime SIGSEGV is reproducible and now characterized.

Filed as **#611** with full backtrace + crash-site disassembly + likely upstream hypothesis.

**Crash bisection result:** the segfault is during `effect/src/Utils.ts__init` (the 11th module-init `bl` from `_main`). Crash site is a `js_array_indexOf` / `js_array_includes`-shaped runtime helper called with `x0 = 0x1` — i.e. someone passed `1` as the array-header pointer. Standalone repro of the load-bearing line (`Utils.ts:793-794`, `standard.effect_internal_function(() => new Error().stack)?.includes(...)`) **runs clean** in isolation, so the crash is triggered by **state pollution from one of the 10 earlier-init'd modules** (likely `Types`, `HKT`, `Function`, `Equivalence`, `Predicate`, `GlobalValue`, or one of the `internal/*` helpers).

#321 stays open until #611 lands.

**Comment by proggeramlug** [comment]
## v0.5.795 update — #611 fixed, new residual at HashMap.ts

Re-ran the DoD repro on v0.5.795 (after #611 landed). Major progress:

| Phase | v0.5.706 | v0.5.795 |
|---|---|---|
| Modules collected | 362 ✅ | 362 ✅ |
| Codegen failures | 0 ✅ | 0 ✅ |
| Missing-symbol refs | 0 ✅ | 0 ✅ |
| Link | clean ✅ | clean ✅ |
| Boots into main | ❌ SIGSEGV | ✅ |
| Init runs cleanly | ❌ Utils.ts SIGSEGV | ❌ HashMap.ts TypeError |
| `result: 42` | — | — |

The segfault is gone. The crash has migrated forward in the init chain — **`Utils.ts` (11th init) now completes cleanly**, but **`HashMap.ts` (26th init) throws `TypeError: value is not a function`** during its top-level bindings. The throw is a controlled `try`/`catch`-compatible exception (no SIGSEGV), just uncaught.

Filed as **#671** with full backtrace, throw-site mapping (`throw_not_callable` in `closure.rs:774` — `js_closure_callN` got an invalid func_ptr), HashMap.ts top-level analysis, standalone-repro attempt (didn't trigger — the bug needs the full 25-module init prefix), and pointers for the next investigator.

#321 stays open until #671 lands. After that, the next thing to validate is whether the remaining 336 module inits run cleanly, then user code (`Effect.runSync(Effect.succeed(42))`) actually produces `result: 42`.

**Comment by proggeramlug** [comment]
## v0.5.809 update — #671 fixed, new residual at Schema.ts (init #309/362)

Re-ran the DoD repro on v0.5.809 after #671 landed. The HashMap.ts throw is gone; **308 of 362 module inits now run cleanly** before a new throw:

```
TypeError: (number).slice is not a function
    at <anonymous>
```

Bisected to **`effect/src/Schema.ts__init`** — the 309th call from `_main` (out of 362). Schema.ts is the schema-validation library, 11,443 lines, by far the largest module in Effect. Throw site is `js_native_call_method`'s primitive-receiver catch-all in `object.rs:6488-6506` — codegen emitted `js_native_call_method(value, "slice", args)` somewhere in Schema.ts's top-level eval, but `value` carries a number NaN-box tag instead of string/array.

Filed as **#685** with full backtrace, init-order mapping, throw-site analysis, and pointer to the most likely culprit (`static params = params.slice()` at Schema.ts:960, inside the `TemplateLiteralParser` factory's returned class).

| Phase | v0.5.706 | v0.5.795 | v0.5.809 |
|---|---|---|---|
| Boots into main | ❌ SIGSEGV | ✅ | ✅ |
| Inits cleared before crash | — | 25/362 (HashMap) | **308/362 (Schema)** |
| `result: 42` | — | — | — |

Two more sub-issues to land and #321 should finally reach the DoD. 308/362 is a big leap from 25/362 — each landed fix is unblocking ~280 module inits worth of forward progress. The remaining ~54 modules are Schema.ts + everything topologically downstream.

**Comment by proggeramlug** [comment]
## v0.5.862 update — #685 fixed, new residual in Schema.ts (~132 bytes deeper)

Re-ran the DoD repro on v0.5.862. #685 (`(number).slice`) is gone; init runs ~132 bytes / 33 instructions further into Schema.ts's body before the next throw:

```
TypeError: pipe is not a function
    at <anonymous>
```

Bisected via lldb backtrace + entry-`.o` relocations to **the same module (`effect/src/Schema.ts__init`), just deeper inside it**.

Throw site is `object.rs:6521` (`js_native_call_method` real-object catch-all from #648). Almost certainly the top-level `class X extends String$.pipe(...)` pattern starting at Schema.ts:4970 (`Lowercased`, `Uppercased`, `Capitalized`, ..., ~30 such classes); `String$` itself is `class String$ extends make<string>(AST.stringKeyword) {}` — a class extending a factory return value. Perry's class-method dispatch isn't finding `pipe` on the inheritance chain when the base is a function-call result.

Filed as **#711** with full backtrace, init-order mapping, throw-site analysis, and a 7-line minimal repro of the surface shape (which works clean in isolation — needs the full Effect init prefix to trip).

| Phase | v0.5.795 | v0.5.809 | v0.5.862 |
|---|---|---|---|
| Boots into main | ✅ | ✅ | ✅ |
| Crash site | HashMap.ts (#26) | Schema.ts (~+12012) | Schema.ts (~+12144) |
| `result: 42` | — | — | — |

Each landed fix peels off one more layer. Same module two version-bumps in a row suggests Schema.ts will gate the next several fixes — it's 11,443 lines of heavy generics, factory-returned classes, and Pipeable-protocol top-level evaluation. After Schema.ts there are still ~50 modules left (Cron, FiberRef, Layer, …) that we haven't even tested yet.

**Comment by proggeramlug** [comment]
## v0.5.893 update — #711 fixed, new residual in ParseResult.ts

Re-ran the DoD repro. #711 (Schema.ts `pipe is not a function`) is gone — Schema.ts is no longer the blocker. The crash has moved to **`effect/src/ParseResult.ts__init`** (a Schema.ts dependency, so earlier in topological order):

```
TypeError: value is not a function
    at <anonymous>
```

Bisected to `ParseResult.ts:230`: `export class ParseError extends TaggedError("ParseError")<{ readonly issue: ParseIssue }>`. Throw is from `closure.rs::throw_not_callable` — `js_closure_callN` got an invalid func_ptr.

The shape is the same family as #711 — `class X extends FactoryCall(...)<...>` — but here `TaggedError` is a cross-module function import from `effect/src/Data.ts` that returns a class declared inside an object literal:

```ts
export const TaggedError = <Tag extends string>(tag: Tag) => {
  const O = { BaseEffectError: class extends Error<{}> { readonly _tag = tag } }
  ;(O.BaseEffectError.prototype as any).name = tag
  return O.BaseEffectError as any
}
```

Filed as **#740** with backtrace, init-order mapping, throw-site analysis, and a 12-line standalone repro that hits a related TypeError (`Cannot read properties of undefined (reading 'issue')`) — faster iteration target than the full Effect rebuild loop. Effect's `Data.ts` defines several factories with this same inner-class-in-object-literal shape (`TaggedClass`, `TaggedEnum`, `Class`, ...), so a fix likely unblocks several downstream modules at once.

| Phase | v0.5.795 | v0.5.862 | v0.5.893 |
|---|---|---|---|
| Boots into main | ✅ | ✅ | ✅ |
| Crash module | HashMap.ts | Schema.ts | **ParseResult.ts** |
| `result: 42` | — | — | — |

**Comment by proggeramlug** [comment]
## v0.5.910 update — #740 fixed, new residual in HashRing.ts (with standalone repro!)

Re-ran the DoD repro. #740 (ParseResult.ts / TaggedError) is gone. Crash moved to **`effect/src/HashRing.ts__init`** — throw `TypeError: value is not a function`.

Root-caused to a **mis-compiled object literal** at HashRing.ts:51-67 (`const Proto = { [TypeId]: TypeId, [Symbol.iterator]() {...}, pipe() {...}, ...Inspectable.BaseProto, toJSON() {...} }`).

**This is the first blocker in the chain with a tight 20-line standalone repro** (no Effect / npm needed) — filed as **#809**. Standalone, the bug manifests as silent corruption rather than a throw:
- `Object.keys(Proto).length` = 2 (should be 5) — computed-key props + cross-module spread dropped
- `inst.toJSON()` returns `"1970-01-01T00:00:00.000Z"` — own `toJSON` mis-resolves to `Date.prototype.toJSON`
- `inst[TypeId]` is `undefined` — computed-string-key prop never stored

The combination of computed-key entries interleaved with an object-spread (`...nsMember`) is the trigger; likely the spread path allocates a fresh object and discards the computed-key entries accumulated before it (cf. #590's allocate-vs-mutate history). Should be much faster to land than the prior five (#611/#671/#685/#711/#740) since it doesn't need the 55MB Effect rebuild loop to verify.

| Phase | v0.5.862 | v0.5.893 | v0.5.910 |
|---|---|---|---|
| Crash module | Schema.ts | ParseResult.ts | **HashRing.ts** |
| Standalone repro | full Effect | full Effect | **20-line ✅** |
| `result: 42` | — | — | — |

**Comment by proggeramlug** [comment]
## Status update — V8-free AOT (post-#1696), perry 0.5.1028

The board reset since the last update here (v0.5.910): **V8/`perry-jsruntime` was removed in #1696**, so Effect must compile natively (`perry.compilePackages: ["effect"]`) — there is no interpreter fallback. Re-ran end-to-end on effect@3.21.2. Big progress:

| Phase | v0.5.910 | now |
|---|---|---|
| Modules collected | 362 ✅ | 362 ✅ |
| Codegen | crash chain | **0 failures ✅** |
| Link | — | **clean ✅** |
| Boots + runs all module inits | ❌ (HashRing) | **✅** |
| Core `runSync(succeed(42))` | — | **✅ `result: 42`** (deep import, byte-for-byte with node) |
| Canonical DoD `import { Effect }` | — | ❌ (two latent bugs below) |

The old crash chain (#611/#671/#685/#684/#711/#740/#809) is all cleared at compile/link/boot. **Effect's core actually runs natively now.**

### Landed: PR #1756 (two fixes)

1. **`fix(hir)` — uppercase `import * as X` namespace-member call now invokes the member.** `Effect.succeed(42)` was returning the `succeed` function uncalled (the "uppercase = class" heuristic mislabeled namespace imports; post-V8 that path returned the member without calling). Fixed + minimal repro.
2. **`fix(runtime)` — guard `ensure_key_in_keys_array` against a non-heap `keys_array`** so a miscompiled object's garbage slot can't SIGBUS inside `js_array_length`.

Both are regression-safe (normal `Object.defineProperty`/`Object.create` unaffected; uppercase now lowers identically to lowercase).

### Remaining blockers (filed as granular sub-issues)

These are **pre-existing latent codegen bugs that #1756 exposes** by making Effect's internal namespace calls actually execute:

- **#1757** — `makeGenericTag`'s `tag` local is mis-assigned by codegen (a valid-tagged pointer into string data, not the `Object.create` result). Full-tree-init-order dependent. Downstream → `TypeError: has is not a function`. This is the next blocker on the deep-import path.
- **#1758** — `Schema.ts__init` throws `_tag` of undefined on the barrel import (`import { Effect } from "effect"`).

### Definition of done

`import { Effect } from "effect"; Effect.runSync(Effect.succeed(42))` → `result: 42` still requires #1757 + #1758 (and a named-namespace-reexport dispatch variant for the barrel `Effect` name). Keeping #321 open until then. The deep import (`import * as Effect from "effect/Effect"`) needs only #1757.

**Comment by proggeramlug** [comment]
## ✅ Definition of Done met — Effect compiles + runs end-to-end natively (perry 0.5.1031, V8-free AOT)

Re-verified the canonical DoD on current `main` (commit `2581c10f9`). All outputs are byte-for-byte with `node --experimental-strip-types`.

**Canonical DoD** — barrel import, all ~360 modules incl. `Schema.ts`:
```ts
import { Effect } from "effect";
const result = Effect.runSync(Effect.succeed(42));
console.log("result:", result);
```
```
$ perry compile test_minimal.ts -o out && ./out
result: 42          # exit 0  ✅  (matches node)
```

**Bonus criteria** also pass:
```ts
import { Effect } from "effect";
// pipe + map
Effect.runSync(Effect.succeed(42).pipe(Effect.map((x: number) => x + 1)))   // → 43 ✅
// Effect.gen + yield*
const program = Effect.gen(function* () {
  const x = yield* Effect.succeed(10);
  const y = yield* Effect.succeed(32);
  return x + y;
});
Effect.runSync(program)                                                      // → 42 ✅
```

The deep import (`import * as Effect from "effect/Effect"`) also produces `result: 42`.

### What cleared the final blockers

The remaining barrel-import chain (Schema.ts `_tag` crash + the class-expression-identity issue #1772) was resolved by the class-object foundation epic **#1785** — subtickets **#1786 / #1787 / #1788 / #1789** (PRs #1792, #1793, #1795, #1797, #1800, #1809, #1810, #1820) — plus the Effect-specific fixes #1817, #1818, #1819, #1822, #1834, #1853, #1863, #1871, #1888, #1894, #1912, #1961, #1969, #1974, #1975. Earlier groundwork: PR #1756 (uppercase namespace-member call + `keys_array` guard) and PR #1763 (WeakMap/WeakSet dynamic dispatch + TS param-property defaults).

Effect now runs as native AOT — no V8, no interpreter fallback. Closing confirmed.
