### ISSUE TITLE
TS-widget SwiftUI codegen: shared FFI helpers + @_cdecl emitted per-widget → cross-file 'private' inaccessibility / duplicate symbols (regression from #1294)

### ISSUE THREAD

**Issue by proggeramlug** [PerryTS/perry#5069]
**Perry version:** 0.5.1161
**Follow-up to:** #1294 (its two original bugs — `perry_nanbox_string` redeclared, unqualified `.utf8` — are fixed on 1161; the `private` fix it landed introduced the bug below) and #1179.

## Summary

For a `perry/widget` bundle with multiple `Widget({...})` declarations, the SwiftUI codegen emits the shared perry-runtime FFI helpers **once per widget**, marked `private`. Because `swiftc *.swift` compiles all generated files as one module:

- `private` (current) → the helpers are file-scoped, but they're **called from a different generated file** (`{Name}.swift`), so the call site can't see them → *inaccessible* error.
- non-`private` → N copies across N glue files → *redeclaration* error (the original #1294 failure).

Neither per-file visibility works. The shared FFI block must be emitted **once per bundle**, `internal`.

## Repro

```
perry compile widgets/index.ts --target ios-widget --app-bundle-id com.example.app -o /tmp/out/
```

with ≥2 `Widget(...)` declarations in `widgets/index.ts`.

## Error

```
QuickStatsWidget.swift:46:26: error: 'perry_get_string' is inaccessible due to 'private' protection level
   let resultJson = perry_get_string(resultPtr)
QuickStatsWidgetGlue.swift:18:14: note: 'perry_get_string' declared here
   private func perry_get_string(_ val: Int64) -> String { ... }
```

`crates/perry-codegen-swiftui/src/emit.rs::emit_glue` (~L654) emits per widget, into `{Name}Glue.swift`:

```swift
@_silgen_name("js_nanbox_string")
private func perry_nanbox_string(_ s: UnsafePointer<CChar>) -> Int64
private func perry_nanbox_string(_ s: String) -> Int64 { ... }
@_silgen_name("js_get_string_pointer_unified")
private func perry_get_string_ptr(_ val: Int64) -> UnsafePointer<CChar>
private func perry_get_string(_ val: Int64) -> String { ... }
@_silgen_name("perry_runtime_widget_init")
private func perry_runtime_widget_init()
```

…but `{Name}.swift` (emit.rs:234 / :369) calls `perry_get_string(resultPtr)` — a different file.

## Bug 1b — `@_cdecl` shared-storage bridge also per-widget → duplicate C symbol

Same `emit_glue`, when `appGroup` is set (common to all widgets in a bundle):

```swift
@_cdecl("perry_widget_shared_storage_get")
func widgetSharedStorageGet(_ keyPtr: Int64) -> Int64 { ... }
```

`@_cdecl` exports a fixed C symbol; ≥2 widgets sharing an app group ⇒ duplicate-symbol link error. Latent today (swiftc fails first) but real.

## Suggested fix

Emit the shared FFI block (the `@_silgen_name` imports, the two `perry_nanbox_string` overloads, `perry_get_string_ptr`/`perry_get_string`, `perry_runtime_widget_init`) **and** the `@_cdecl("perry_widget_shared_storage_get")` bridge **once per bundle**, `internal`, in a single `PerryWidgetRuntime.swift`. Per-widget glue keeps only the widget-unique `@_silgen_name("__widget_provider_<Name>") func __widget_provider_<Name>(...)`.

Touch points: `crates/perry-codegen-swiftui/src/lib.rs::compile_widget` (stop per-widget emission) + the multi-widget assembly driver in `crates/perry/src/commands/compile/targets.rs` (emit the shared file once).

## Downstream (not yet reachable)

Because this fails at swiftc, the `.appex` **link** step is still unverified: the widget extension link reportedly doesn't pull in `libperry_runtime.a` / the TS provider objects (unresolved `perry_runtime_widget_init` / `js_nanbox_string` / `__widget_provider_*`). Once swiftc passes, please confirm the link resolves these — it's the real gate on shipping TS widgets.

## Repro project

GSC Master (TopSites/QuickStats/DailyChange widgets via `perry/widget`). Happy to test a fix.
