### PR TITLE
fix(regex): do not cap RegExp operations by work (#10164)

### PR DESCRIPTION
**Pull request by proggeramlug**
Fixes the `RangeError` half of #10164.

## Problem

Every RegExp operation ran under one fixed `Budget` of 100,000,000 work units (`perex_api::WORK`), so valid programs that Node completes threw `RangeError: Regular expression work limit exceeded`:

- a 32,000-unit non-ASCII `split` and a 60,000-unit global `replace` — the per-search seek charge summed to about n²/4 (the cost placement is on #10164);
- once #10174 makes split and replace linear, linear work too: at n = 1,000,000 records the benchmark `split` (15M units) and `replace` (11M units) reach the end of the input and throw, where Node takes 240 and 281 ms.

## Why no cap

No finite allowance separates valid programs from pathological ones. Perex's charge per subject unit is set by the program, not the subject:

| linear pattern | work units per subject unit |
|---|---:|
| `/x/g`, no match | 1.0 |
| `/\w+/g` | 9.4 |
| split `/[,; ]+/`, sticky attempt per position | 27.6 |
| `/([a-z]+)([0-9]+)/g` | 59.2 |
| `/\w(?=[\w,; ]{32})/g` | 223.6 |

Any cap throws on some large linear input, and a quadratic pattern on a short subject never reaches it. JavaScript engines never abort matching for work. The Perex maintainer set out three options — no cap, a length-scaled cap, or a wall-clock/cancellation guard — and the maintainer chose no cap, for parity.

## Change

`WORK` becomes `usize::MAX`, with the reasoning documented on the constant.

- Searches still run in `QUANTUM` slices with a GC poll between them, so collection and cancellation keep working.
- The scratch, program and output **memory** limits are unchanged.
- A catastrophic pattern now runs as long as it does in Node instead of throwing.

The existing tests that exercise `ExecError::WorkLimit` all pass their own small budgets (0, 3, 37, …), so they still cover the error mapping and accounting.

## Test

`gc::tests::runtime_roots::perex_work_policy` runs one valid, linear search that charges about 1.2e8 units and asserts that it completes and charged more than the former limit. The search is a failing 32-unit lookahead at every position of 540,000 units.

The pattern deliberately has **no required literal**. My first candidate, `\w(?=\w{32}!)`, charged only 600,040 units, because admission rejects a search whose required `!` never occurs in one pass. So a witness has to defeat that shortcut to prove anything.

- **Sabotage:** with the old 100,000,000 cap restored, the test fails with "a valid search must complete without a work-limit error".
- All 78 `gc::tests::runtime_roots::perex*` tests and all 71 `regex::` unit tests pass, and rustfmt is clean.
- Verified locally (GitHub runners are not in use).

## Related

- #10174 — binds the subject and program once per split/replace/match, plus a forward-search split. That makes those operations linear, and this PR lets linear work of any size complete.
- The quadratic time half of #10164 (the per-search seek on non-ASCII storage) needs Perex 0.1.2's search-from-position API. That wiring waits for perex 0.1.2 to clear Perry's 7-day publish-age window.

https://claude.ai/code/session_01Da12JXeG5XuVBma5yWp5C9

## Summary by CodeRabbit

* **Bug Fixes**
  * Regular expression operations can now process valid workloads exceeding the previous work limit without being prematurely aborted.
  * Large, valid searches continue to respect memory safeguards, cancellation, and runtime scheduling while completing successfully.
  * Repeated split, replace, and global-match operations on the same input can run more efficiently.

### CODE REVIEW

**Comment by proggeramlug** [comment]
## Full perry-runtime lib suite, replayed locally at `f9073c461`

GitHub runners are not in use, so this ran on an Ubuntu x86_64 build host with nightly-2026-08-20 and LLVM 22.1.8: `cargo test -p perry-runtime --lib -- --test-threads=1`.

**3,678 passed, 1 failed, 4 ignored.**

The single failure is `native_stack::tests::stack_top_respects_custom_thread_stack_sizes` (`native_stack.rs:53`, "bound must belong to this worker"). It is red on `main` itself: reproduced identically on `origin/main` 50e08e91d, as recorded on #10115, and `main`'s own CI reports it too. Nothing in this PR touches `native_stack.rs`.

https://claude.ai/code/session_01Da12JXeG5XuVBma5yWp5C9

**Comment by proggeramlug** [comment]
Heads-up for landing this on current `main` (`6874a9eb73`, which now has #10174): the new test `crates/perry-runtime/src/gc/tests/runtime_roots/perex_work_policy.rs` calls `api::execute_with_resources` with 6 arguments, but #10174 added a 7th `reuse: Option<&Reuse>` parameter, so `perry-runtime`'s lib test target stops compiling:

```
error[E0061]: this function takes 7 arguments but 6 arguments were supplied
   --> crates/perry-runtime/src/gc/tests/runtime_roots/perex_work_policy.rs:41:13
    = argument #7 of type `Option<&Reuse<'_, '_>>` is missing
```

The fix is one line, passing `None` after `&mut || Ok(()),`. The two PRs compile on their own, but not together. I hit this assembling a combined train and have dropped #10176/#10181 from my train, since your lane is landing the regex stack ("Next in order: #10176, #10181, #10183" on #10187).

**Comment by proggeramlug** [comment]
Rebased onto `main` at `6874a9eb73`, now that #10174 has landed (train 177, #10187), and pushed as `b895f32e5`.

Both PRs merged cleanly as text, but the combined tree did not compile. This PR's `perex_work_policy` test calls `api::execute_with_resources` with 6 arguments, and #10174 added a seventh `reuse: Option<&Reuse>` parameter. The fix passes `None` there, which is what a standalone call already means. No runtime code changed.

Re-verified on the rebased head (perrymaster, `--locked`, no publish-age override):
- fmt; `cargo check -p perry-runtime --lib --tests`: no warnings outside the known `global_this_webassembly.rs` dead code
- `gc::tests::runtime_roots::perex`: 83 passed; `regex::`: 71 passed
- Fault injection: restoring `WORK = 100_000_000` fails `perex_operation_allowance_admits_linear_work_beyond_the_former_limit`. The source was restored byte-identical afterwards.

Before the rebase, the full replay of the old head `c61d617cb` matched main exactly: `perry-runtime --lib` 3678 passed, the only failure being `native_stack::tests::stack_top_respects_custom_thread_stack_sizes`, which is red on main; lint script tier 76/77 with the same public-baseline freshness failure as main; regex-off check with 0 warnings. The merge train revalidates the combined tree before landing.

https://claude.ai/code/session_01Da12JXeG5XuVBma5yWp5C9

**Comment by proggeramlug** [comment]
Landed on `main` via merge train 178 (#10192) as `0ec7ee1a81`..`ca1f65deaa`, with the version bump `df886c6445` (0.5.1550). Validation of the combined tree is in #10192. Closing, since this landed through the train.

https://claude.ai/code/session_01Da12JXeG5XuVBma5yWp5C9
