### PR TITLE
test(link): regression guard for #8907 — full-stdlib links without the http ext archive

### PR DESCRIPTION
**Pull request by steinybot**
## Summary

Adds an end-to-end regression test for #8907: a program that references a `cgu.0`-only stdlib symbol (`new Blob([...])`) with no `node:http` import must link and run. The bug itself was already fixed by #5983 (v0.5.1239) — this fills the missing regression coverage.

## Changes

- `crates/perry/tests/issue_8907_ext_http_cgu_link.rs`: compile `const b = new Blob(["x"]); console.log(b.size)`, assert `perry compile` links and the binary prints `1`.
- `changelog.d/9243-ext-http-cgu-link-regression-test.md`: changelog fragment.

Root cause (for context): #5831 leaked `external-http-client-pump` into perry-stdlib's `full` feature, which declares `js_ext_http_*` symbols defined only in `perry-ext-http`. That archive is linked per-program by the compile driver, and only when the program imports `node:http`. The release packs stdlib into one monolithic `cgu.0` object, so referencing any symbol it uniquely defines (`Blob` → `js_blob_new`) pulls the whole member and its unresolved http references into the link. #5983 drops the pump from `full`; the driver activates it only when `node:http` is imported and `perry-ext-http` is on the link line.

Complements the manifest-level guard in `issue_8587_prebuilt_stdlib_http_isolation` (asserts `full` does not enable the external http pumps) with a real end-to-end link.

## Related issue

Refs #8907. Fixed in code by #5983 (v0.5.1239); this PR adds regression coverage.

## Test plan

```
cargo test -p perry --test issue_8907_ext_http_cgu_link
# test cgu0_program_links_without_http_ext_archive ... ok
cargo fmt -p perry -- --check   # clean
```

Also confirmed against the shipped binaries: released `perry 0.5.1220` fails the same repro with 14 undefined `js_ext_http_*` symbols; current `main` links and runs it (prints `1`). The fix commit was located by `git bisect` over `cgu=1` dist builds → #5983.

- [ ] `cargo build --release` clean
- [ ] `cargo test --workspace` passes (ran the scoped `-p perry --test issue_8907_ext_http_cgu_link` instead — test-only change)
- [x] Added a `#[test]` in the affected crate
- [ ] (if CLI / stdlib / runtime API changed) Updated `docs/src/` — n/a, test-only
- [ ] (if touching a platform UI backend) Built `-p perry-ui-<backend>` — n/a

## Screenshots / output

Released 0.5.1220 (the bug):

```
Undefined symbols for architecture arm64:
  "_js_ext_http_agent_dispatch_method", referenced from:
  ... (14 total)
ld: symbol(s) not found for architecture arm64
```

Current `main` (fixed): `Wrote executable`, runs, prints `1`.

## Checklist

- [x] I have NOT bumped the workspace version or edited CLAUDE.md / CHANGELOG.md (maintainer handles these at merge)
- [x] My commits follow the `feat:` / `fix:` / `docs:` / `chore:` prefix convention
- [ ] I've read CONTRIBUTING.md and agree to the Code of Conduct

## Summary by CodeRabbit

- **Tests**
  - Added an end-to-end regression test ensuring programs using `Blob` compile, link, run successfully, and produce the expected output without requiring unrelated HTTP functionality.

- **Documentation**
  - Added a changelog entry documenting the regression coverage and confirming the issue is resolved.

### CODE REVIEW

**Comment by proggeramlug** [comment]
Merged. Thanks — the root-cause writeup is the valuable part here, and I verified its premise directly rather than taking it on trust.

Confirmed in the built archive: `js_blob_new` is defined in `…perry_stdlib.c4d96a4db3fa0ceb-cgu.0.rcgu.o` — exactly the monolithic object your analysis names — and that archive currently carries **0** undefined `_js_ext_http_*` references. So the coupling is genuinely gone on `main`, which is why the test passes, and `Blob` is the right minimal trigger: pulling the member for a `cgu.0`-only symbol is what would drag the unresolved references back into the link. "The node:http framing is a red herring" is the insight that makes this test possible at all — a test written against the *reported* symptom would have imported `node:http` and never reproduced anything.

The test itself is built to be able to fail, which is what I care about in a regression guard:

- `--no-cache`, so it can't pass on a cached artifact;
- it **runs** the binary and asserts `size == 1` rather than only asserting the compile exited zero — so a compile that succeeded without linking the member coherently is still caught;
- `CARGO_BIN_EXE_perry`, so it tests the compiler built from the tree rather than whatever is on PATH.

`perry --test issue_8907_ext_http_cgu_link`: 1 passed, exit 0. `ci_e2e_scope.py` picks the suite up automatically from the diff (`crates/perry/tests/` suites are diff-driven; the manual `_CODEGEN_SUITES` list is only for `perry-codegen`), so it will actually run per-PR rather than being dark until nightly — worth saying because a suite that CI never invokes is the exact failure mode #7708 and #9193 were about.

One nit I could not push to your branch, since it's on your fork: `cargo fmt --all -- --check` wants the `std::fs::write(...)` call at line 33 wrapped across lines, which fails the `warnings`/fmt lint gate. I'm landing that as an immediate follow-up on `main` rather than bouncing the PR back to you for a line break.
