### PR TITLE
fix(runtime): EventTarget methods must live on the prototype so subclasses inherit them (#6301)

### LINKED ISSUE #5931: Using cac with default command resulting in error
## What happened

```
TypeError: value is not a function
    at <anonymous>
```

## What you expected

It should output correct help details:
```
util

Usage:
  $ util

Commands:
  build [...files]  Build files

For more info, run any command with the `--help` flag:
  $ util build --help
  $ util --help

Options:
  -v, --version  Display version number
  -h, --help     Display this message
```

## Minimal reproduction

```sh
npm install cac
```
add the `cac` to `perry.allow.compilePackages`

```ts
import cac from 'cac';
const cli = cac();

cli.command('build [...files]', 'Build files')
   .option('--minify', 'Minify output')
   .action((files, opts) => {
     console.log('Building files:', files, 'Opts:', opts.minify)
   })

// DEFAULT command - This block causes the ERROR
cli.command('')
  .action(() => {
    cli.outputHelp()
  })

cli.help()
cli.parse()
```

Command you ran:

```bash
perry compile main.ts -o app

./app
```

## Environment

- **Perry version**: 0.5.1220
- **Host OS**: macOS 26.5.2
- **Target**: native
- **Rust toolchain**: rustc 1.95.0 (59807616e 2026-04-14) (Homebrew)
- **Installed via**: brew

## Diagnostic output

```
Environment Checks
──────────────────
  ✓ perry version: 0.5.1220
  ✓ update status: up to date
  ✓ clang (LLVM codegen): Apple clang version 21.0.0 (clang-2100.1.1.101)
  ✓ system linker (cc): Apple clang version 21.0.0 (clang-2100.1.1.101)
  ✓ runtime library: /opt/homebrew/lib/libperry_runtime.a
  ✓ project config (perry.toml): found
  ✓ compatibility reports (#849): mode=ask (sent=0, suppressed-by-dedup=0, queued=0, cache=empty)
```

## Anything else

When run using `bun main.ts` it runs without error.

### LINKED ISSUE #6301: runtime: `class X extends EventTarget` doesn't inherit addEventListener/dispatchEvent (root cause of #5931, breaks cac)
## Summary

`class X extends EventTarget` does not inherit `addEventListener` / `removeEventListener` / `dispatchEvent`. The subclass instance reports them as `undefined`, and calling one throws `TypeError: value is not a function`.

## Repro

```ts
class Bus extends EventTarget {}
const b = new Bus();
console.log("typeof dispatchEvent:", typeof b.dispatchEvent);
console.log("typeof addEventListener:", typeof b.addEventListener);
```

| | output |
|---|---|
| node 26 | `function` / `function` |
| perry `main` @ 0960415ad | `undefined` / `undefined` |

Verified on a clean `origin/main` build.

## Root cause (suspected)

`EventTarget` appears to be implemented as **name-keyed native method dispatch** (`crates/perry-runtime/src/event_target.rs`, registered in `object/global_this_tables.rs`) rather than as real function properties resident on a prototype object. The telling detail: on a **plain** `new EventTarget()`, `t.addEventListener(...)` **works as a call** (the listener fires) but `typeof t.addEventListener` is still `undefined`. Because there is nothing on the prototype, a subclass inherits nothing.

`class A extends EventTarget {}; class B extends A {}` is also `undefined`.

Likely the same shape as the prototype work in #6147/#6148/#6149: the methods need to live on a real prototype object rather than being resolved by receiver name.

## Impact

This breaks any package whose class extends `EventTarget`. It is the **actual root cause of #5931** ("Using cac with default command resulting in error"): cac v7's `CAC` class is `class CAC extends EventTarget`, and every matched command path calls `this.dispatchEvent(...)`, so any matching command dies with `TypeError: value is not a function`. (#5931's title is misleading — it is not about the default command; a command with no `.action()` fails too.)

### PR DESCRIPTION
**Pull request by proggeramlug**
## Root cause

`EventTarget`'s method surface never existed as **values**. `addEventListener` /
`removeEventListener` / `dispatchEvent` were only a compile-time lowering
(`perry-codegen/src/lower_call/event_target.rs`) that fires when the receiver's
*static class name* is literally `EventTarget`. Nothing lived on a prototype and
nothing was resolvable at runtime, which produced two symptoms:

* on a plain `new EventTarget()`, `t.addEventListener(...)` **worked as a call**
  (the static lowering caught it) but `typeof t.addEventListener` was
  `"undefined"` — there was no property to read;
* a `class Bus extends EventTarget {}` instance has the static class name `Bus`,
  so the lowering never fired and **nothing was inherited at all**:
  `typeof b.dispatchEvent === "undefined"`, and calling it threw
  `TypeError: value is not a function`. Two-level (`class B extends A extends
  EventTarget`) was equally dead.

The `EventTarget` global also had no reserved class id, so
`js_register_class_parent_dynamic` — which resolves a builtin superclass by name
through `global_builtin_constructor_class_id` — left every `extends EventTarget`
subclass **parentless** in the class registry. There was no edge to inherit
across.

This is the actual root cause of **#5931** ("Using cac with default command
resulting in error"): cac v7's `CAC` is `class CAC extends EventTarget`, and its
matched-command path calls `this.dispatchEvent(new CustomEvent(...))`
(`cac/dist/index.js:543`), so every matching command died with
`TypeError: value is not a function`. Verified directly — see below.

## Fix

Resolve the methods off the receiver's **class chain** — the same mechanism
`Event` subclasses already use (`is_event_instance`) — and materialize them as
bound-method closures, which is the established shape for exactly this problem
(`abort_signal_method_bind` for AbortSignal, and the
value-read-materializes-a-bound-method work of #6281).

* **`event_target.rs`** — reserve `CLASS_ID_EVENT_TARGET` (`0xFFFF_2406`).
  `js_event_target_new` stamps it on the instance header (mirroring
  `construct_event`'s `CLASS_ID_EVENT`). `class_chain_is_event_target` walks the
  registered parent chain to it, and `is_event_target` accepts a receiver that is
  a target *either* by the legacy `_eventTarget` marker (the plain instance) *or*
  by class chain (a subclass at any depth). `event_target_method_bind` mints a
  1-capture bound-method closure per name, with the receiver stored as NaN-boxed
  bits so the GC's closure scan keeps it alive and relocates it.
* **`object/instanceof.rs`** — map `"EventTarget"` to that id in
  `global_builtin_constructor_class_id`, so `js_register_class_parent_dynamic`
  wires the `Subclass → EventTarget` registry edge at class-definition time. This
  single line is what makes inheritance work at any depth: `B extends A extends
  EventTarget` reaches the base through the ordinary `A → EventTarget` edge, with
  no codegen chain-walking.
* **`object/field_get_set/get_field_by_name_tail.rs`** — the **value-read** path
  (`typeof b.dispatchEvent`, `const add = t.addEventListener`). Placed
  deliberately **last** in the tail, so an own property and a real class-vtable
  method (a subclass that *overrides* `dispatchEvent`) are resolved earlier and
  keep winning.
* **`object/native_call_method.rs`** — the **dynamic-call** path (a fused
  `bus.dispatchEvent(ev)` / `this.addEventListener(...)`). Placed immediately
  before the terminal `"<m> is not a function"` throw, so it can only ever turn a
  guaranteed failure into a working call; every own-field / vtable /
  prototype-chain lookup above it is untouched.
* **`perry-codegen/src/expr/instance_misc1.rs`** — the literal-RHS `instanceof`
  id table, keeping `x instanceof EventTarget` consistent with the runtime id.

A subclass instance never runs `js_event_target_new`, so its hidden state
(marker + listener bag + max-listener count) is seeded lazily on first
listener/dispatch use (`seed_event_target_state`). That keeps the subclass
constructor lowering completely untouched — no `super()` arm, no implicit-ctor
arm, no new codegen path. Every heap value there is rooted in a
`RuntimeHandleScope` and re-read from its handle at each use, because both
`js_object_alloc` and `key()` (string interning) can allocate and GC-move the
receiver.

## Before / after

```ts
class Bus extends EventTarget {}
const b = new Bus();
console.log(typeof b.dispatchEvent, typeof b.addEventListener);
const t = new EventTarget();
console.log(typeof t.addEventListener);
```

| | `main` @ `0960415ad` | this branch | node |
|---|---|---|---|
| `typeof b.dispatchEvent` | `undefined` | `function` | `function` |
| `typeof b.addEventListener` | `undefined` | `function` | `function` |
| `typeof t.addEventListener` (plain base) | `undefined` | `function` | `function` |
| `b.dispatchEvent(new Event("x"))` | `TypeError: value is not a function` | listener fires | listener fires |
| `class B extends A extends EventTarget` | `undefined` | `function` | `function` |
| `b instanceof EventTarget` | `false` | `true` | `true` |

## cac / #5931 — verified end to end

`npm i cac@7`, `perry.compilePackages: ["cac"]`, a default command plus a named
command, `cli.parse([...])`:

* **`main` @ `0960415ad`:** `TypeError: value is not a function` — the exact
  #5931 failure.
* **this branch:** runs, and is **byte-identical to `node --experimental-strip-types`**.

## Verified

* **`test-files/test_gap_6301_event_target_subclass.ts`** (new) — byte-identical
  to `node --experimental-strip-types`. Covers: method value-reads + `typeof` on
  the plain base and on a subclass; listeners actually firing through a subclass;
  two-level `B extends A extends EventTarget`; a subclass with its own
  constructor + fields calling `this.dispatchEvent(...)` (the cac shape); a
  detached `.bind()`-ed method value; `removeEventListener` actually removing;
  per-instance listener bags (no cross-instance leakage); a subclass **override**
  still winning over the inherited method; `{ once: true }`; `instanceof
  EventTarget` from base, subclass and two-level subclass; and `Event` /
  `CustomEvent` construction + `.detail` unchanged.
* Same fixture is byte-identical under `PERRY_GC_FORCE_EVACUATE=1
  PERRY_GC_VERIFY_EVACUATION=1` (the lazy seeding and the bound-method captures
  survive a moving collection).
* `cargo test -p perry-runtime`: **1264 passed, 0 failed** (`--test-threads=1`).
  The parallel run shows one failure in
  `url::node_compat::tests::path_to_file_url_posix_preserves_relative_trailing_slash`
  — a cwd-dependent test that passes in isolation and on an unmodified
  `origin/main` worktree; unrelated to this change.
* `cargo fmt --all -- --check` clean; `scripts/check_file_size.sh`,
  `scripts/gc_store_site_inventory.py` and the addr-class audit all pass on the
  files this PR touches. (The addr-class gate is already red on clean `main` for
  `crates/perry-runtime/src/map.rs` — the pre-existing ratchet that #6297
  addresses, not this branch.)
* A/B'd the neighbouring event tests against an unmodified `origin/main` build:
  `test_gap_events_import_4995` and `test_issue_850_eventemitter` diverge
  **identically** before and after — both are pre-existing EventEmitter gaps, not
  regressions from this PR.

## Scope note

`super.dispatchEvent(event)` from inside a subclass override still does not reach
the base. That is a pre-existing, orthogonal limitation of `super.<method>()`
into any *native* base — `class E extends EventEmitter { emit() { …
super.emit(…) } }` is worse today (the override does not even run) — and it wants
its own issue rather than a change to the super-call lowering here.

Fixes #6301
Fixes #5931

## Summary by CodeRabbit

- **New Features**
  - `EventTarget` now exposes `addEventListener`, `removeEventListener`, and `dispatchEvent` as real method values that work when inherited and accessed dynamically (including detached reads).
  - `EventTarget` is now correctly recognized by `instanceof`, covering plain instances and subclasses.
  - Listener state is initialized lazily for recognized `EventTarget` instances to support consistent per-instance behavior.
- **Bug Fixes**
  - Correct behavior for multi-level inheritance, sibling subclasses, `{ once: true }`, and listener removal.
  - Subclass `dispatchEvent` overrides take precedence over the inherited implementation.

### CODE REVIEW

File: crates/perry-runtime/src/object/field_get_set/get_field_by_name_tail.rs [hunk 1]
```diff
@@ -1968,6 +1968,25 @@ pub(crate) fn get_field_by_name_object_tail(
...
+        // depth). Deliberately LAST in the tail: an own property and a real
+        // class-vtable method (a subclass that *overrides* `dispatchEvent`)
+        // are resolved earlier and keep winning.
+        if !key.is_null() && crate::event_target::is_event_target_method_name(key_bytes) {
+            if let Some(bound) =
+                crate::event_target::event_target_method_bind(obj as *mut ObjectHeader, key_bytes)
+            {
+                return JSValue::from_bits(bound.to_bits());
+            }
+        }
```
[the remark this answers is not in the document]
Comment (proggeramlug) [reply crates/perry-runtime/src/object/field_get_set/get_field_by_name_tail.rs:1984]: Verified empirically, and this one doesn't hold — the premise that a class instance can reach here with `keys_array == NULL` is false. Not moving the fallback, but I've documented the invariant and pinned it with fixtures so the next reader doesn't have to re-derive it.

**Why a `class X extends EventTarget` instance never takes the keyless branch**

Every class-instance allocator installs the shape-cached keys array unconditionally:

* `js_object_alloc_class_inline_keys` — `set_object_keys_array(ptr, keys_array)` (`object/alloc.rs:240`)
* `js_object_alloc_class_with_keys` — `set_object_keys_array(ptr, keys_arr)` (`object/alloc.rs:402`)
* `js_object_alloc_class_dynamic_parent` — merges parent+own keys, else delegates to `_with_keys` (`object/alloc.rs:436`)

and the array they install is **never NULL** for a fieldless class — `js_build_class_keys_array` returns a zero-**length** array:

```rust
if field_count == 0 || packed_keys_len == 0 || packed_keys.is_null() {
    let arr = crate::array::js_array_alloc_with_length_longlived(0);   // <- empty, not null
    ...
    return arr;
}
```
(`object/alloc.rs:284`)

`keys_array == NULL` is the state of a *freshly bump-allocated* object (`js_object_alloc`, `js_object_alloc_fast`) before its first by-name store — i.e. `Object.create(proto)` results and bare `js_new_function_construct` instances. A `class` instance is never in that state.

**Empirical check.** I instrumented the tail with a temporary print at the `keys.is_null()` test and at the keyless dead-end return, and ran every shape I could think of that might produce an empty-shaped event target:

| shape | `keys_array` | `typeof x.dispatchEvent` |
|---|---|---|
| `class Bus extends EventTarget {}` (no fields, no ctor) | **non-null** (empty) | `function` |
| subclass with a ctor that assigns nothing | non-null (empty) | `function` |
| two-level `B extends A extends EventTarget` | non-null (empty) | `function` |
| `new Ctor()` through a variable (dynamic `new`) | non-null | `function` |
| `Reflect.construct(Bus, [])` | non-null | `function` |
| `const K = class extends EventTarget {}` | non-null | `function` |
| class returned from a factory | non-null | `function` |
| subclass declared inside a function body | non-null | `function` |
| instance whose only own prop was `delete`d | non-null | `function` |
| `Object.freeze(new Bus())` | non-null | `function` |
| `Object.create(Bus.prototype)` | **NULL** | `function` |

The **`KEYLESS-DEAD-END` probe never fired once** — for any of these, for any of the three method names.

The only receiver that does reach the keyless branch is `Object.create(Bus.prototype)`, and it already resolves correctly *inside* that branch: `resolve_proto_chain_field_with_receiver` (the first thing the keyless branch tries, well before its `return undefined()`) hops to the prototype object, which is itself a shaped, class-id-stamped receiver, and that hop reaches this fallback. I also checked it doesn't leak listeners onto the shared prototype — a listener added via an `Object.create`d receiver does not fire on a sibling `new Bus()`. (Node actually *throws* `Cannot read properties of undefined (reading 'get')` on that shape, since there's no internal slot — so we're strictly more permissive there, not less.)

**What I changed in response**

Rather than move the block (which would put it *ahead* of the own-property and class-vtable lookups and break the subclass-override ordering this PR exists to get right), I:

1. Documented the invariant on `event_target::event_target_value_read`, so the placement is justified where the mechanism lives.
2. Added the empty-shape cases to `test-files/test_gap_6301_event_target_subclass.ts` — empty ctor, dynamic `new`, `Reflect.construct`, class expression, function-local subclass, deleted-own-prop, frozen instance. All byte-identical to `node --experimental-strip-types`, also under `PERRY_GC_FORCE_EVACUATE=1 PERRY_GC_VERIFY_EVACUATION=1`.

Thanks for the push on this — the invariant was load-bearing and undocumented, which is exactly what made the finding plausible.

**Comment by proggeramlug** [comment]
## Rebased on `main` + CodeRabbit review follow-up

Rebased onto `main` (`7a3b48afd`) — clean, no conflicts with the ten PRs that landed since branching (including #6322/#6316, which established the same "user's class chain wins, native is the fallback" ordering this PR relies on).

### The "Major" finding — verified, and it does not hold

CodeRabbit flagged the value-read fallback as dead for class instances with `keys_array == NULL`, which return early at the keyless branch (~line 1521) before reaching it. I chased this empirically rather than taking it either way. **The premise is false: a class instance can't have `keys_array == NULL`.**

All three class-instance allocators (`js_object_alloc_class_inline_keys`, `js_object_alloc_class_with_keys`, `js_object_alloc_class_dynamic_parent`) install the shape-cached keys array unconditionally, and `js_build_class_keys_array` returns a zero-**length** array — never NULL — when the class declares no fields (`object/alloc.rs:284`). `keys_array == NULL` is the pre-first-store state of a bump-allocated object, which a `class` instance is never in.

I instrumented the tail with a temporary print at the `keys.is_null()` test and at the keyless dead-end, then ran every shape I could construct that might yield an empty-shaped event target: fieldless subclass, assign-nothing ctor, two-level subclass, dynamic `new` through a variable, `Reflect.construct`, class expression, factory-returned class, function-local subclass, deleted-own-prop instance, frozen instance, `Object.create(Bus.prototype)`. **The keyless-dead-end probe never fired once.** Every shape reports `function` for all three methods, matching node. Full table + reasoning in the [review thread](https://github.com/PerryTS/perry/pull/6311#discussion_r3568138621).

The one receiver that *does* take the keyless branch is `Object.create(Bus.prototype)` — and it resolves correctly *within* that branch, via the `resolve_proto_chain_field_with_receiver` hop that runs well before its `return undefined()`. I also confirmed it doesn't leak listeners onto the shared prototype. (Node throws on that shape outright, so we're more permissive there, not less.)

Moving the block earlier, as suggested, would place it *ahead* of the own-property and class-vtable lookups and break the subclass-override ordering that is the whole point of this PR.

### What changed in response

1. **Documented the invariant** on the new `event_target::event_target_value_read` — the tail's call site now points at it. It was load-bearing and undocumented, which is exactly what made the finding plausible.
2. **Pinned it with fixtures**: `test_gap_6301_event_target_subclass.ts` gains the empty-shape cases (empty ctor, dynamic `new`, `Reflect.construct`, class expression, function-local subclass, deleted-own-prop, frozen instance).
3. **Kept the tail under the file-size cap** — the added rationale had pushed `get_field_by_name_tail.rs` to 2009 lines, so the body moved into `event_target.rs` (which has headroom) behind `event_target_value_read`. Behaviour-identical: same name gate, same bind, same point in the walk. `get_field_by_name_tail.rs` is now 1990 lines.

### Verification

* `test-files/test_gap_6301_event_target_subclass.ts` — byte-identical to `node --experimental-strip-types`, and byte-identical again under `PERRY_GC_FORCE_EVACUATE=1 PERRY_GC_VERIFY_EVACUATION=1`.
* **cac v7 + default command (#5931)** — re-verified end to end on the rebased branch: a default `[...files]` command plus a named `build <target>` command, both dispatching through `this.dispatchEvent(new CustomEvent(...))`. Byte-identical to node.
* `cargo test -p perry-runtime` — **1278 passed, 0 failed**.
* `cargo fmt --all -- --check` clean; `scripts/check_file_size.sh` clean.
* `test_gap_events_import_4995` / `test_issue_850_eventemitter` still diverge exactly as they do on `main` — the pre-existing **EventEmitter** gaps already noted in the PR description, untouched by this branch.

### One real bug found along the way — filed separately

While hunting for a shape that reaches the keyless path, I found an unrelated, **pre-existing** gap: an *immediately-constructed* class expression loses its builtin parent edge.

```ts
new (class extends EventTarget {})()   // instanceof EventTarget → false; addEventListener → undefined
new (class extends Event {})("tick")   // instanceof Event → false; .type → undefined   ← predates this PR
```

It hits `Event` (long-standing) exactly as it hits `EventTarget`, so it's a general `ClassExprFresh`-vs-builtin-parent registration hole, not something this PR introduced or should grow to cover — the const-bound form (`const K = class extends EventTarget {}`) works fine here. Filed as #6336.
