### PR TITLE
fix: dynamic array-method dispatch dropped the thisArg — extracted builtin method as callback with thisArg (#6658)

### LINKED ISSUE #6658: compile: Array.prototype.forEach(set.add, set) on an Any destructured-for-of receiver throws 'Set.prototype.add called on incompatible receiver' — pi wall #7
Wall #7 of the pi coding-agent bring-up (tracker #6564; prior: #6593, #6604, #6644, #6649, #6651, #6652 all fixed). With the six fixes applied (current: PR #6656), `pi-native --help`/`--version` die during module init with:

```
TypeError: Method Set.prototype.add called on incompatible receiver
    at pi-bundle.mjs:203827
```

(line from the refreshed `--debug-symbols` build `dist/pi-native-dbg`; the stripped build says `at <anonymous>`.)

**Site**: `@babel/types/lib/index.js` (webpack-wrapped CJS factory), the alias-expansion init loop, pi-bundle.mjs:203827:

```js
for (const { types: e4, set: t4 } of n7.allExpandedTypes) for (const r4 of e4) {
  const e5 = n7.FLIPPED_ALIAS_KEYS[r4];
  e5 ? e5.forEach(t4.add, t4) : t4.add(r4);   // ← line 203827
}
```

Node: `Array.prototype.forEach(callback, thisArg)` calls the extracted native `t4.add` (`Set.prototype.add`) with `this = t4` — works. Perry: the receiver reaching the native method fails the Set brand check.

**11-line repro** (node: `sizes: 3 1`; perry: the TypeError above, rc=1):

```ts
const FLIPPED: any = { A: ["x", "y"], B: null };
const allExpandedTypes: any[] = [
  { types: ["A", "B"], set: new Set() },
  { types: ["B"], set: new Set() },
];
for (const { types: e4, set: t4 } of allExpandedTypes) {
  for (const r4 of e4) {
    const e5 = FLIPPED[r4];
    e5 ? e5.forEach(t4.add, t4) : t4.add(r4);
  }
}
console.log("sizes:", allExpandedTypes[0].set.size, allExpandedTypes[1].set.size);
```

**Already ruled out** (each of these works in isolation, byte-identical to node — the bug needs the combined shape, so it is NOT a plain forEach-thisArg gap):

```ts
["a","b"].forEach(s.add, s);                       // typed receiver: OK
const t4: any = new Set(); ["a"].forEach(t4.add, t4); // Any receiver: OK
const add = t4.add; add.call(t4, "q");             // extraction + .call: OK
for (const { set: t4 } of rows) ["a"].forEach(t4.add, t4); // destructured for-of: OK
e5 ? e5.forEach(t4.add, t4) : t4.add("z");         // ternary shape: OK
```

Suspect subsystem: the interaction of nested for-of + object-pattern loop bindings + the two-armed ternary dispatch on an Any receiver — some path re-materializes/wraps `t4.add` (or the thisArg) so the native Set method's brand check sees a non-Set receiver. Possibly the same family as the alternating `t4.add(r4)` direct-call arm specializing the method and poisoning the extracted-callback arm (or vice versa).

Also on the road ahead (NOT this wall, hit while probing): the bundle-shape `var GaxiosInterceptorManager = class extends Set {}` inside a CJS factory, `new exportsObj.GaxiosInterceptorManager()` then `.add(...)` → `TypeError: add is not a function` (builtin-subclass through a class EXPRESSION + property-read `new`; family of #6232 `class extends Array`). gaxios instantiates these per Gaxios instance — it will bite once init gets past @babel/types.

Repro binaries: `secret-tests/pi-target/dist/pi-native` (stripped) and `pi-native-dbg` (debug symbols, prints the bundle line), both built from PR #6656's branch; `pi-native.pre6652` reproduces wall #6 for contrast. `HOME=$(mktemp -d) ./pi-native --version`.

### PR DESCRIPTION
**Pull request by proggeramlug**
## Root cause

Pi bring-up wall #7 (tracker #6564). At pi-bundle.mjs:203827 (@babel/types' alias-expansion loop), `e5 ? e5.forEach(t4.add, t4) : t4.add(r4)` threw `TypeError: Method Set.prototype.add called on incompatible receiver`; node prints `sizes: 3 1`.

It is NOT the ternary, NOT method extraction, and NOT a plain forEach-thisArg gap (the issue's five ruled-out shapes all work): the **dynamic method-dispatch tower** (`js_native_call_method` → the dense-array arms in `native_call_method/handle_methods.rs`) **dropped `args[1]` — the thisArg — for the whole Array.prototype callback family** (`forEach`/`map`/`filter`/`some`/`every`/`find`/`findIndex`/`findLast`/`findLastIndex`) and dispatched to the dense helpers, which deliberately bind the callback's `this` to `undefined` (the spec rule for an *absent* thisArg).

The static lowering (`lower_array_method.rs`) already routes explicit-thisArg calls through the this-binding `js_arraylike_*` engine. A receiver only reaches the dynamic tower when codegen can't prove its type — in the bundle, `e5` is an object member read through a **dynamic key** (`FLIPPED[r4]`), which defeats flow typing. That is why every statically-provable simplification of the shape worked and only the combined form reproduced. The extracted `t4.add` resolves to the identity-preserving brand-checking `Set.prototype.add` thunk (#3662), reads `IMPLICIT_THIS = undefined`, and throws. A lexically-capturing closure callback on the same path silently ran with the wrong `this` instead (`arr.map(fn, thisArg)` observed `this !== thisArg` — also fixed).

## Fix

- `native_call_method/handle_methods.rs`: mirror the static rule in the dynamic tower — with a thisArg present (`args_len >= 2`), route the nine-method family through `dispatch_arraylike_read_method`, whose `ThisGuard` binds the thisArg around each callback call (real-array receivers keep a fast element path inside the engine). `flatMap` has no engine entry and shares the same thisArg gap on the static path too; untouched here.
- `collection_proto_thunks.rs`: node appends V8's `NoSideEffectsToString` rendering of the receiver to the brand-check TypeError (`... called on incompatible receiver #<Object>` / `undefined` / `5.5` / `[object Array]` / `#<Foo>` / `Error: boom`). `throw_incompatible_receiver` now renders the receiver the same way, so the throwing cases are **message-identical** to node. (No builtin property attributes touched — the #6335 gotcha territory was left alone.)

## Tests

- `crates/perry/tests/issue_6658_extracted_builtin_method_thisarg.rs`: the issue's 11-line combined shape verbatim; the five previously-ruled-out simpler shapes as regression anchors; the minimal dynamic-key trigger with `Set.prototype.add`, `Map.prototype.set`, and `Array.prototype.push` extracted as callbacks; this-binding asserted across the whole nine-method family; eight brand-check throw cases with node-v26-byte-identical messages (`undefined`, `#<Object>`, cross-brand `#<Set>`, `5.5`, `abc`, `null`, `#<Foo>`, `[object Array]`).
- `test-parity/node-suite/object/extracted-builtin-method-callback-thisarg.ts`: same coverage through the parity runner — 100% vs node v26.
- Suites: perry-runtime lib **1426/0** (`--test-threads=1`), perry-codegen lib 209/0, perry-hir lib 246/0, node-suite object module 26/26, existing `test_gap_3662_collection_brand_check` still 100%. `cargo fmt --check` clean on touched files.

## Validation on the real target

Full pi recompile with this fix: `HOME=$(mktemp -d) ./pi-native --version` → `0.0.0` rc=0 and `--help` → the 167-line usage rc=0, **both byte-identical (stdout+stderr) to `node pi-bundle.mjs`** — GATE 1 of the pi bring-up reached; no wall #8 on these entry points.

Stretch-goal assessment (gaxios `class extends Set` losing `add`, issue family #6232): probed — `class A extends Set {}` + static `new` works, direct class-expression `new` works; what fails is **construction through a dynamic path** (`new exportsObj.X()` / `new obj.A()`): the Map/Set backing init (`js_map_set_subclass_init`) is emitted by codegen only at *static* `new` sites (`lower_call/new_helpers.rs::emit_native_instance_base_init`), so dynamic-new never installs the backing for ANY native base (Set, Map, Event, EventEmitter, …). That is the full #6232 builtin-subclass-construction feature (class-id→native-base registry + dynamic-new runtime wiring + ctor-arg seeding), not a bounded Set-only fix in this PR's subsystem — documented on #6232 instead.

**Stacks on #6656** (branched from `fix/6652-global-proto-members`; merge that first).

Fixes #6658

https://claude.ai/code/session_01JuiiePQfrXhAFD9fuCygB9

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed extracted array-like and collection callback handling so an explicitly provided `thisArg` is preserved across methods like `forEach`, `map`, `filter`, `some`, `every`, and the `find*` family.
  * Improved brand-check `TypeError` messages for incompatible receivers by including clearer, Node/V8-style receiver rendering.
* **Tests**
  * Added regression tests ensuring parity with Node/V8 for extracted callback `thisArg` binding and exact error message text for receiver-related failures.

### CODE REVIEW

**Comment by proggeramlug** [comment]
Rebased onto main after #6656's squash-merge landed — the branch now carries only the #6658 commit (338f87efe); the stacks-on-#6656 note in the description is obsolete.

**Comment by proggeramlug** [comment]
CodeRabbit's finding fixed in c8-amended head: the receiver is now rooted in a RuntimeHandleScope across the `toString`-key allocation and the object pointer re-derived through the rewritten handle before `own_data_field_by_name`/`class_id`. Verified with cargo check -p perry-runtime.
