### PR TITLE
fix(codegen): #5657 — class extends native builtin must not run the builtin as a parent function

### LINKED ISSUE #5657: REGRESSION: class extends native builtin (ArrayBuffer/Map/Promise/TypedArray/…) broke — 23 subclass-builtins cases (#5613)
## Severity: HIGH (class extends native builtin)

The 2026-06-25 full re-sweep (main @ `9a3d2469d`, perry 0.5.1206, node v26.3.0) raised overall parity to 94.1%, but **23 `class extends <native builtin>` cases newly broke** vs the prior sweep — every `subclass-builtins` test under both `language/statements/class` and `language/expressions/class`:

```
subclass-ArrayBuffer.js       TypeError: ArrayBuffer is not a function
subclass-DataView.js          TypeError: DataView is not a function
subclass-Function.js          TypeError: Function is not a function
subclass-Promise.js           TypeError: Promise is not a function
subclass-RegExp.js            TypeError: RegExp is not a function
subclass-Map.js               TypeError: Constructor Map requires 'new'
subclass-Set.js               TypeError: Constructor Set requires 'new'
subclass-WeakMap.js           TypeError: Constructor WeakMap requires 'new'
subclass-WeakSet.js           TypeError: Constructor WeakSet requires 'new'
subclass-BigInt64Array.js     TypeError: Constructor %TypedArray% requires 'new'
subclass-BigUint64Array.js    TypeError: Constructor %TypedArray% requires 'new'
```
(× both `statements/class` and `expressions/class`) plus `built-ins/ArrayBuffer/isView/arg-is-dataview-subclass-instance.js`.

### Root
Window points squarely at **#5613 (`6de00e8f5`)** — *"class extending a function base must run the parent constructor (preserve derived identity)"*. That path now treats a native builtin base (`ArrayBuffer`, `Map`, `Promise`, `%TypedArray%`, …) as a plain callable function base and tries to invoke it as the parent constructor, but native builtins reject being called without `new` / aren't resolved as a callable in that path → `X is not a function` / `Constructor requires 'new'`. `extends` of a native builtin must route to the builtin's construct path, not the run-parent-as-function path.

This inflates the #5592 class-tail count (240 → 257); the true class tail is lower.

### Smaller co-regressions from the same batch (3)
- `annexB/language/eval-code/direct/func-switch-case-eval-func-no-skip-param.js` + `func-switch-dflt-…` — `binding is not initialized` (likely #5636 B.3.3 over-reach on switch-param eval).
- `built-ins/RegExp/unicode_restricted_quantifiable_assertion.js` — `RegExp("(?=.)*","u")` must throw `SyntaxError` under `/u` (regression from #5629 quantified-lookaround acceptance).

### Measure
```
scripts/test262_subset.py --root /root/test262 --dir language/statements/class language/expressions/class built-ins/ArrayBuffer --jobs 6
```
on the internal Linux sweep host.

### PR DESCRIPTION
**Pull request by proggeramlug**
Fixes #5657.

## Regression

The 2026-06-25 re-sweep flagged **23 `subclass-builtins` test262 cases newly broken** vs the prior sweep — every `class extends <native builtin>` under both `language/statements/class` and `language/expressions/class`, plus `built-ins/ArrayBuffer/isView/arg-is-dataview-subclass-instance`:

```
subclass-ArrayBuffer  TypeError: ArrayBuffer is not a function
subclass-Map          TypeError: Constructor Map requires 'new'
subclass-Promise      TypeError: Promise is not a function
subclass-BigInt64Array TypeError: Constructor %TypedArray% requires 'new'
…
```

## Root cause

The window pointed at **#5613** (`6de00e8f5`). That commit added a branch in the inline-`new` lowering: for a no-own-ctor class with a dynamic parent (`extends_expr`), resolve the decl-time-registered parent value and dispatch it on `this` via `js_fetch_or_value_super`, so a function-value base (zod 4's `$constructor`) runs its body.

But `class X extends ArrayBuffer / Map / Promise / %TypedArray% / RegExp / Function / …` is **also** captured as `extends_expr` — a bare builtin Ident doesn't resolve through `lookup_class`. Its parent value is a builtin constructor that rejects being *called* as a plain function, so `js_fetch_or_value_super` → `js_native_call_value` threw.

## Fix

Gate the inline-`new` dynamic-parent super on `!is_other_builtin_constructor_name(extends_name)`, mirroring the **identical guard the explicit `Expr::SuperCall` arm already applies** (`expr/this_super_call.rs`). Perry can't give a subclass instance a builtin's internal slots, so `super()` to such a base is a best-effort no-op; the instance is already allocated with the correct dynamic-parent prototype chain, so `instanceof` (and `ArrayBuffer.isView`, which walks that chain) hold.

`Request`/`Response`/`Error` are deliberately **not** in that set — they need the dispatch (native fetch-handle attach / callable error thunk) — so they keep running it, and the #5613 function-value-parent path is untouched.

## Verification

A repro covering all 11 listed builtins, an `Error` subclass, the #5613 dynamic-function parent, and `ArrayBuffer.isView` on a `DataView` subclass — all pass:

```
PASS ArrayBuffer / DataView / Function / Promise / RegExp / Map / Set
PASS WeakMap / WeakSet / BigInt64Array / BigUint64Array
PASS Error-subclass
PASS dynamic-fn-parent(#5613)
isView: true   instanceof DataView: true
```

`perry-codegen` 128/128.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling for `new` calls that extend native built-in constructors, avoiding an invalid `super(...)` fallback when the parent can’t be called.
  * Added a safe no-op behavior for `super(...)` when the resolved parent matches specific uncallable native built-in constructors.
  * Ensured the uncallable-constructor check is applied consistently across related `new`/`super` resolution paths.

### CODE REVIEW

File: crates/perry-codegen/src/lower_call/new.rs [hunk 1]
```diff
@@ -1677,7 +1677,28 @@ fn lower_new_impl(
...
+        // `Expr::SuperCall` arm already applies via `is_other_builtin_constructor_name`
+        // (`expr/this_super_call.rs`). Request/Response/Error are deliberately NOT
+        // in that set: they DO need the dispatch (native fetch-handle attach /
+        // callable error thunk), so they keep running it.
+        let parent_is_uncallable_builtin = class
+            .extends_name
+            .as_deref()
+            .map(crate::expr::is_other_builtin_constructor_name)
+            .unwrap_or(false);
+        if !found_inherited_ctor && class.extends_expr.is_some() && !parent_is_uncallable_builtin {
```
[the remark this answers is not in the document]
Comment (proggeramlug) [reply crates/perry-codegen/src/lower_call/new.rs:1706]: Addressed in the runtime: `js_fetch_or_value_super` now no-ops by VALUE via `is_uncallable_builtin_super_parent` (kept in lockstep with codegen's `is_other_builtin_constructor_name`), so aliased parents like `const AB = ArrayBuffer; class X extends AB {}` are caught too — verified now constructs. Request/Response/Error stay dispatchable.
