### ISSUE TITLE
Node API compatibility epic: node:path upstream lexical, win32/posix, glob, and namespace semantics parity

### ISSUE THREAD

**Issue by andrewtdiz** [PerryTS/perry#3822]
## Summary

`node:path` has mostly complete export presence on current `origin/main`, but upstream Node's own `path` corpus still exposes deterministic runtime behavior gaps. This is narrower than the closed broad path epics: it is specifically about making Perry pass the upstream-derived `path` behavior cases after the recent manifest/export cleanup.

## Evidence

Baseline:
- Perry `origin/main@42851afea273b6cf6772becb2b751489c5d24eb1` (`fix(node:zlib): stream.params retunes compression level + validates args (#3817)`)
- Node sparse checkout `nodejs/node v22.x@7b1b943` (`Working on v22.22.4`)
- Release build: `cargo build --release -p perry -p perry-runtime -p perry-stdlib`

Focused upstream sample command:

```sh
scripts/node_core_subset.py \
  --root /tmp/perry-nodejs \
  --api path \
  --max-per-api 50 \
  --sample-cap 50 \
  --perry-bin /Users/dutchess/Documents/PerryTS/perry/target/release/perry \
  --report /tmp/perry-node-core-path-origin.json
```

Result:

```text
path pass=6 diff=0 rt-fail=9 compile-fail=0 node-skip=2 parity=40%
```

Runtime failures from the report:

```text
test-path-extname.js                 Uncaught exception:
test-path-glob.js                    Uncaught exception: Missing expected exception
test-path-join.js                    TypeError: value is not a function
test-path-makelong.js                TypeError: Cannot read properties of undefined (reading 'posix')
test-path-normalize.js               Uncaught exception: Expected values to be strictly equal
test-path-relative.js                TypeError: value is not a function
test-path-resolve.js                 TypeError: Cannot read properties of undefined (reading 'win32')
test-path-zero-length-strings.js     Uncaught exception: Expected values to be strictly equal
test-path.js                         Uncaught exception: Expected values to be strictly equal
```

Node skips under the shim were `test-path-dirname.js` and `test-path-parse-format.js`, so they should not be charged to Perry until the shim can execute them.

Export shape is not the main blocker anymore. Node v22 reports 17 enumerable entries for each of `path`, `path/posix`, and `path/win32`; Perry's API manifest reports the same named surface plus `default` for each module:

```text
path:       18 entries -> _makeLong, basename, default, delimiter, dirname, extname, format, isAbsolute, join, matchesGlob, normalize, parse, posix, relative, resolve, sep, toNamespacedPath, win32
path/posix: 18 entries -> _makeLong, basename, default, delimiter, dirname, extname, format, isAbsolute, join, matchesGlob, normalize, parse, posix, relative, resolve, sep, toNamespacedPath, win32
path/win32: 18 entries -> _makeLong, basename, default, delimiter, dirname, extname, format, isAbsolute, join, matchesGlob, normalize, parse, posix, relative, resolve, sep, toNamespacedPath, win32
```

Duplicate check found only closed path issues/epics such as #3604, #3246, #2990, #2991, #2993, #2683, #1728, #810, and #681. No open `node:path` API compatibility epic appears to cover this current upstream failure set.

## Scope

Bring `node:path`, `path/posix`, and `path/win32` into parity for the upstream-derived behavior failures above:

- POSIX and win32 lexical outputs for `extname`, `join`, `normalize`, `relative`, `resolve`, zero-length strings, and the broader `test-path.js` corpus.
- `path.posix` / `path.win32` namespace object access and dynamic method dispatch where upstream tests currently hit `undefined` or `value is not a function`.
- `_makeLong` / `toNamespacedPath` behavior across POSIX and win32 namespaces.
- `matchesGlob` error and matching semantics, especially win32 separator/backslash/globstar behavior.
- Keep the extra ESM `default` export aligned with the broader export-hygiene work tracked in #3804 if that remains intentional outside CJS parity.

## Acceptance

- Add curated upstream-derived fixtures under `test-parity/node-suite/path` for the failing shapes above.
- `./run_parity_tests.sh --suite node-suite --module path` passes for the new/updated path coverage.
- A focused upstream radar run no longer shows Perry runtime failures for the currently failing sample:

```sh
scripts/node_core_subset.py \
  --root vendor/nodejs \
  --api path \
  --max-per-api 75 \
  --sample-cap 50 \
  --report /tmp/perry-node-core-path.json
jq '.totals, .per_api, .samples' /tmp/perry-node-core-path.json
```

**Comment by proggeramlug** [comment]
Closing this **umbrella/epic tracker** as superseded by granular per-gap tracking.

Perry tracks Node/TypeScript parity gaps as **granular, per-gap issues** — that is the workable backlog the maintainer prefers, rather than umbrella/epic roll-ups that coordinate or re-scope other epics. The concrete leaf gaps remain (or should be filed) as focused issues and are addressed by PRs that auto-close the specific leaf they fix; closing this epic loses no implementation work, only the duplicate coordination framing. If a consolidated tracker for this module/area is still wanted, feel free to reopen.

**Comment by andrewtdiz** [comment]
I am taking a focused first cut from this issue. Current `origin/main@ed633ca58` has `./run_parity_tests.sh --suite node-suite --module path` at 91/92 with one reproducible mismatch: `node-suite/path/toNamespacedPath/make-long-alias`. Planned PR scope: align `path._makeLong` / `path.toNamespacedPath` alias behavior and namespace identity for top-level, `path.posix`, and `path.win32`, while preserving the now-green broader path lexical coverage.

**Comment by andrewtdiz** [comment]
Opened PR #3833 for the focused `path._makeLong` / `toNamespacedPath` default namespace dispatch mismatch: https://github.com/PerryTS/perry/pull/3833

Current verification includes the focused fixture and full `node-suite/path` run passing 92/92 on Node 25.9.0 baseline.
