### ISSUE TITLE
Node API compatibility epic: node:querystring and node:string_decoder legacy text codec behavior parity

### ISSUE THREAD

**Issue by andrewtdiz** [PerryTS/perry#3825]
## Summary

`node:querystring` and `node:string_decoder` have useful curated coverage and mostly-present export shapes, but current upstream Node samples still find deterministic runtime divergence. This is a second-pass legacy text-codec epic: preserve the existing green curated coverage, then close the remaining behavior, validation, and compiler/language blockers that prevent Perry from matching Node's own tests.

## Evidence

Baseline:
- Perry `origin/main@ffebfca51c97500a93074a4338241fc5e44b4fff` (`fix(node:fs): add disposable mkdtemp and path error parity (#3814)`)
- Node sparse checkout `nodejs/node v22.x@7b1b943` (`Working on v22.22.4`)
- Release build: `cargo build --release -p perry -p perry-runtime -p perry-stdlib`

Claimed API surface from `target/release/perry --print-api-manifest`:

```text
querystring     8 entries -> decode, default, encode, escape, parse, stringify, unescape, unescapeBuffer
string_decoder  7 entries -> StringDecoder, encoding, end, lastChar, lastNeed, lastTotal, write
```

Focused upstream radar command:

```sh
scripts/node_core_subset.py \
  --root /tmp/perry-nodejs \
  --api querystring string_decoder \
  --max-per-api 50 \
  --sample-cap 50 \
  --perry-bin /Users/dutchess/Documents/PerryTS/perry/target/release/perry \
  --report /tmp/perry-node-core-small-builtins.json
```

Relevant result from the combined run:

```text
querystring      pass=0 diff=0 rt-fail=4 compile-fail=0 node-skip=0 parity=0%
string_decoder   pass=0 diff=0 rt-fail=3 compile-fail=0 node-skip=0 parity=0%
```

Upstream runtime-failure samples:

```text
querystring/test-querystring-escape.js              Expected values to be strictly equal
querystring/test-querystring-maxKeys-non-finite.js  Cannot convert undefined or null to object
querystring/test-querystring-multichar-separator.js The expression evaluated to a falsy value
querystring/test-querystring.js                     (boolean).runInNewContext is not a function
string_decoder/test-string-decoder-end.js           write is not a function
string_decoder/test-string-decoder-fuzz.js          write is not a function
string_decoder/test-string-decoder.js               Expected values to be strictly equal
```

The broad `test-querystring.js` case uses `vm.runInNewContext`, so it may need to be distilled before charging all of that file directly to querystring; keep it in the radar, but make the actionable fixtures smaller and API-specific.

Curated suite cross-checks on the same build:

```sh
./run_parity_tests.sh --suite node-suite --module querystring
```

```text
Parity Pass:  47
Parity Fail:  1
Compile Fail: 11
Output mismatch:
  node-suite/querystring/unescape/unescape-buffer
Compile failures:
  node-suite/querystring/options/custom-codec-return-values
  node-suite/querystring/options/custom-encoder
  node-suite/querystring/options/parse-decode-plus
  node-suite/querystring/options/parse-decode-uri-component
  node-suite/querystring/options/parse-options-combined
  node-suite/querystring/options/separator-coercion
  node-suite/querystring/options/stringify-encode-uri-component
  node-suite/querystring/options/stringify-options-combined
  node-suite/querystring/parse/custom-decoder-errors
  node-suite/querystring/parse/empty-and-separators
  node-suite/querystring/parse/null-prototype
```

```sh
./run_parity_tests.sh --suite node-suite --module string_decoder
```

```text
Parity Pass:  34
Parity Fail:  0
Compile Fail: 1
Compile failure:
  node-suite/string_decoder/validation/error-codes
```

Duplicate check found only closed legacy text-codec issues/epics such as #3604, #2941, #2937, #3031, #3032, #3033, #2676, #1182, #1176, #1175, and #1174. No open `node:querystring` / `node:string_decoder` Node API compatibility epic appears to cover this current upstream failure set.

## Scope

Close the remaining legacy text-codec parity gaps:

- `querystring.escape()` coercion, surrogate/URIError behavior, object `toString`/`valueOf` fallback, and Symbol TypeError behavior.
- `querystring.parse()` `maxKeys` handling for `Infinity`, `NaN`, and their string forms.
- Multi-character separator/equal handling and null-prototype result shape.
- Custom encoder/decoder option callbacks, including returned non-string values and thrown decoder errors.
- `unescapeBuffer` namespace/default access and runtime behavior, where curated parity currently sees `undefined` despite the manifest claiming it.
- `StringDecoder` instance `write()` / `end()` availability in upstream CommonJS tests, split-buffer/end-state behavior, fuzz alignment with `Buffer.toString()`, and validation error-code coverage.
- Classify and, where appropriate, split out non-API blockers such as `vm.runInNewContext`, object/null-prototype support, or callable prototype-method lowering if those are the real cause of a specific fixture failure.

## Acceptance

- Add or update curated upstream-derived fixtures under:
  - `test-parity/node-suite/querystring`
  - `test-parity/node-suite/string_decoder`
- Existing green curated fixtures remain green.
- These commands pass without querystring/string_decoder parity failures or compile failures attributable to these modules:

```sh
./run_parity_tests.sh --suite node-suite --module querystring
./run_parity_tests.sh --suite node-suite --module string_decoder
```

- A focused upstream radar run no longer shows Perry runtime failures for distilled `querystring` and `string_decoder` behavior cases:

```sh
scripts/node_core_subset.py \
  --root vendor/nodejs \
  --api querystring string_decoder \
  --max-per-api 75 \
  --sample-cap 50 \
  --report /tmp/perry-node-core-text-codecs.json
jq '.totals, .per_api, .samples' /tmp/perry-node-core-text-codecs.json
```

- Any remaining `node-skip` or harness-dependent files are documented with a reason instead of being counted as Perry API behavior failures.

**Comment by andrewtdiz** [comment]
I am taking a first focused PR cut here. Planned scope: legacy text-codec behavior shared by `node:querystring` and `node:string_decoder`, starting from the current curated failures and keeping it to deterministic API behavior rather than `vm`/harness blockers. I will preserve existing green coverage, add upstream-derived parity fixtures for the failing cases I touch, and leave any unrelated language or harness blockers documented rather than silently counting them as module fixes.

**Comment by proggeramlug** [comment]
Closing this **umbrella/epic tracker** as superseded by granular per-gap tracking.

Perry tracks Node/TypeScript parity gaps as **granular, per-gap issues** — that is the workable backlog the maintainer prefers, rather than umbrella/epic roll-ups that coordinate or re-scope other epics. The concrete leaf gaps remain (or should be filed) as focused issues and are addressed by PRs that auto-close the specific leaf they fix; closing this epic loses no implementation work, only the duplicate coordination framing. If a consolidated tracker for this module/area is still wanted, feel free to reopen.

**Comment by andrewtdiz** [comment]
Update after checking latest `origin/main@ed633ca58`: the curated suites referenced here now pass locally with Node 25.9.0 as baseline: `querystring` is 59/59 and `string_decoder` is 35/35. I do not have `vendor/nodejs` or `/tmp/perry-nodejs` in this worktree, so I cannot currently reproduce the upstream-radar failures from the issue body. I am not opening a no-op PR from this claim and will move to another currently reproducible Node compatibility cut.
