### ISSUE TITLE
REGRESSION: class extends native builtin (ArrayBuffer/Map/Promise/TypedArray/…) broke — 23 subclass-builtins cases (#5613)

### ISSUE THREAD

**Issue by proggeramlug** [PerryTS/perry#5657]
## Severity: HIGH (class extends native builtin)

The 2026-06-25 full re-sweep (main @ `9a3d2469d`, perry 0.5.1206, node v26.3.0) raised overall parity to 94.1%, but **23 `class extends <native builtin>` cases newly broke** vs the prior sweep — every `subclass-builtins` test under both `language/statements/class` and `language/expressions/class`:

```
subclass-ArrayBuffer.js       TypeError: ArrayBuffer is not a function
subclass-DataView.js          TypeError: DataView is not a function
subclass-Function.js          TypeError: Function is not a function
subclass-Promise.js           TypeError: Promise is not a function
subclass-RegExp.js            TypeError: RegExp is not a function
subclass-Map.js               TypeError: Constructor Map requires 'new'
subclass-Set.js               TypeError: Constructor Set requires 'new'
subclass-WeakMap.js           TypeError: Constructor WeakMap requires 'new'
subclass-WeakSet.js           TypeError: Constructor WeakSet requires 'new'
subclass-BigInt64Array.js     TypeError: Constructor %TypedArray% requires 'new'
subclass-BigUint64Array.js    TypeError: Constructor %TypedArray% requires 'new'
```
(× both `statements/class` and `expressions/class`) plus `built-ins/ArrayBuffer/isView/arg-is-dataview-subclass-instance.js`.

### Root
Window points squarely at **#5613 (`6de00e8f5`)** — *"class extending a function base must run the parent constructor (preserve derived identity)"*. That path now treats a native builtin base (`ArrayBuffer`, `Map`, `Promise`, `%TypedArray%`, …) as a plain callable function base and tries to invoke it as the parent constructor, but native builtins reject being called without `new` / aren't resolved as a callable in that path → `X is not a function` / `Constructor requires 'new'`. `extends` of a native builtin must route to the builtin's construct path, not the run-parent-as-function path.

This inflates the #5592 class-tail count (240 → 257); the true class tail is lower.

### Smaller co-regressions from the same batch (3)
- `annexB/language/eval-code/direct/func-switch-case-eval-func-no-skip-param.js` + `func-switch-dflt-…` — `binding is not initialized` (likely #5636 B.3.3 over-reach on switch-param eval).
- `built-ins/RegExp/unicode_restricted_quantifiable_assertion.js` — `RegExp("(?=.)*","u")` must throw `SyntaxError` under `/u` (regression from #5629 quantified-lookaround acceptance).

### Measure
```
scripts/test262_subset.py --root /root/test262 --dir language/statements/class language/expressions/class built-ins/ArrayBuffer --jobs 6
```
on the internal Linux sweep host.

**Comment by proggeramlug** [comment]
Re-measure 2026-06-26: #5665 fixed 21 of 23 subclass-builtins cases. **2 stragglers remain**: `subclass-SharedArrayBuffer.js` (statements + expressions) — `Expected true but got false` (SharedArrayBuffer-specific, distinct from the function-base path).
