### PR TITLE
fix: Next.js standalone bring-up — walls 36–44 (dynamic-parent classes, forward-capture, super.method, cjs export-hint, self-new in capturing closure)

### PR DESCRIPTION
**Pull request by proggeramlug**
## Next.js 16.2.9 standalone bring-up — walls 36–43

Continues the `compile-as-package` / Next.js work. With these fixes the Next.js standalone server **compiles (auto-optimize, ~124 MB), boots, listens, routes, and runs request handling through to the OpenTelemetry tracer** (previously it died inside the `NextNodeServer` constructor). Each fix has an isolated repro.

| Wall | Fix |
|---|---|
| **36** | Pre-register sibling class names in function-expression bodies (forward refs in cjs IIFE). |
| **37** | Don't hold the class-vtable read lock across a method body (lazy `require()` took the write lock → deadlock). |
| **38** | `class X extends _mod.default` (interop ESM default-export base) ran no base ctor. cjs_wrap hoist guard now scans the `extends` head for IIFE-local refs; `.default` member-extends routes through `extends_expr`; super/`new` use the decl-time-stashed parent (`CLASS_DYNAMIC_PARENT_VALUE`) and invoke a ClassRef parent via `run_class_constructor_on_this_flat`. |
| **39** | Dead `0 && (module.exports = { X: null })` Babel export-hint was extracted as a real named export, overriding the real `_export(exports, { X: () => X })` getter with `undefined`. Shape-2 scan now requires a statement boundary (skips expression context like `0 && (…)`). |
| **40** | Dynamic `require(unresolvable)` now throws a `MODULE_NOT_FOUND`-coded error (Node parity) so `try { require(p) } catch (e) { if (e.code !== 'MODULE_NOT_FOUND') throw }` degrades gracefully (Next swallows the absent instrumentation hook). |
| **41** | Closures forward-capturing a later-declared function-scope `let`/`const` resolved to a `globalThis` read → `ReferenceError` (router-server `initialize()` request handler reads `relativeProjectDir` declared ~400 lines below → HTTP 500). New shared `pre_register_forward_captured_lets` boxes only bindings referenced by an *earlier* closure; preallocs the box at entry (kept out of `hoisted_id_set` so non-hoistable `const = arrow` decls aren't reordered). |
| **42** | `super.method()` on a dynamic-parent class returned a bogus `0.0` (static `extends_name` walk missed). `NextNodeServer.makeRequestHandler`'s `super.getRequestHandler()` → number → "value is not a function". New `js_super_method_call_dynamic` resolves from the registered parent (never the child → no override recursion), drops the registry lock before the call (wall-37 safe). |
| **43** | Wall-41 via destructuring + cjs-IIFE bodies: tracer's `_export(exports, { SpanKind: () => SpanKind })` getter forward-captures the later `const { …, SpanKind } = api` → "SpanKind is not defined". The forward-capture helper now handles array/object destructuring leaves + `{ key }` shorthand and is shared by `lower_fn_expr` (the `const _cjs = (function(){…})()` wrapper). |

### Validation
- `perry-hir`, `perry-codegen`, `perry-runtime`, `perry` test suites pass.
- The TypedArray `typed_array_indexof_includes` "failure" under a full run passes in isolation (known test-pollution flake).
- The 2 `issue_4903_listen_callback_deferred` tests fail on a **pre-existing** auto-optimize linker mismatch (`perry_ffi::error::system_error_value`, code untouched by this PR) — environmental to the worktree, unrelated to these changes.

### Known next blocker (not in this PR)
`new SelfClass(thisAlias.field)` inside a closure that captured `const t = this` mis-binds the new instance's ctor `this` → tracer `BaseContext.setValue` throws. Tracked as wall 44.

## Summary by CodeRabbit

* **Bug Fixes**
  * Reduced false-positive `module.exports = { ... }` export detection when it appears in expression contexts.
  * Fixed `super()` and `super.method(...)` for classes with dynamically resolved parents, including inheritance interop like `module.ClassName.default`.
  * Improved forward-capture/boxing for `let`/`const` (including destructuring) referenced by earlier closures in the same block, plus forward class-name resolution.
  * Updated the `require()` shim fallback to throw a `MODULE_NOT_FOUND` error with a clearer message.
  * Prevented incorrect `new` inlining in a specific constructor/local capture collision scenario.
* **Chores**
  * Updated version/release metadata to **0.5.1168** and refreshed standalone bring-up notes.

### CODE REVIEW

**Comment by proggeramlug** [comment]
---
**Update:** wall 44 added.

| **44** | `new SelfClass(...)` inside a closure that captured a `const t = this` alias mis-bound the new instance's ctor `this` — the inlined constructor's `const t = this` reused a LocalId that is a capture in the lifted closure, so its field writes (`t._cc = …`) landed on the captured outer object and the new instance got no fields. Exactly OpenTelemetry's `BaseContext.setValue` → the Next.js tracer threw `TypeError: Cannot read properties of undefined (reading 'set')` on every request. `lower_new`'s recursion-guard now also redirects to the standalone `<class>_constructor` symbol (which takes `this` as an explicit param) when the enclosing closure captures a local the ctor body declares. |

With wall 44, the server runs request handling all the way through the OTEL tracer into the render pipeline. Next blocker (wall 45, not in this PR): a render error's `catch` handler reads `_iserror.getProperError` where the module-level `_iserror` const resolves to `undefined` in that method scope (and the underlying render error it's trying to report is itself a further wall).

**Comment by proggeramlug** [comment]
**Rebased onto latest `main`** (now includes #5124's `js_node_system_error_value` fix). The 9 wall-36–44 commits are re-applied as one squashed commit on current `main` (they applied cleanly — no code conflicts with main's 15 new commits) so this PR merges without the version/changelog conflicts the stale base would have caused. Builds green; the `http` auto-optimize path compiles and runs again.

**Wall 45 status (not in this PR):** fully diagnosed as a 3-layer bug — (1) `class_field_global_index` returns a wrong fast-path slot for `__perry_cap_*` capture fields at scale, (2) dynamic-parent (`extends _mod.default`) subclasses are under-allocated so inherited captures overflow into the address-keyed overflow side-table, and (3) the parent ctor's by-name capture writes append to the keys-array (allocating), letting GC move `this` mid-construction. A partial fix (by-name capture access + dynamic-parent instance sizing) cleared layers 1–2 but layer 3 (GC-during-construction) remains, so it was reverted to keep this PR clean. Tracked for a focused follow-up.

**Comment by proggeramlug** [comment]
Addressed the rebase + lint failure + CodeRabbit feedback in the latest force-push (`9ccba92`):

**Rebase & lint**
- Rebased onto latest `main` (clean, no conflicts).
- Fixed the failing `lint` job — `cargo fmt` pass over the touched files (`cargo fmt --check` now clean). File-size, gc-store-site, gc-ffi-root, and addr-class gates all pass.

**CodeRabbit fixes (4/5 applied)**
1. ✅ `extract_exports.rs` — the dead `0 && (module.exports = {...})` hint detector now classifies the boundary by the *last non-whitespace token across newlines* (`;`/`}`/`{`/SOF ⇒ statement start; `(`/`&`/`|`/`,`/`=`/`?`/`:`/operators ⇒ expression continuation), so the multiline Babel hint form is caught without regressing the union/object-literal export cases.
2. ✅ `class_constructors.rs` `js_super_method_call_dynamic` — added a fallback to `lookup_prototype_method` (walks the parent chain, drops its read lock before returning so the wall-37 deadlock can't recur) when the class vtable lookup misses, covering function-style parents whose methods live in `CLASS_PROTOTYPE_METHODS` / a synthetic prototype object.
3. ✅ `class_registry.rs` — `CLASS_DYNAMIC_PARENT_VALUE` is now scanned in `scan_class_side_table_roots_mut` (`visit_nanbox_u64_slot` over its values) so a moving GC roots+forwards the stashed dynamic-parent value bits.
4. ✅ `global_this.rs` `js_fetch_or_value_super` — the INT32 (ClassRef) branch now returns `undefined` unconditionally after running the parent ctor on `this`, instead of falling through to `js_native_call_value` with a non-callable NaN-tagged ClassRef.

**Skipped with reason**
5. ⏭️ `class_decl.rs` — keeping `extends_name = Some("default")` for `class X extends _mod.default`. Verified against current code: setting it to `None` regresses the dynamic-parent **super-constructor** path, because `this_super_call.rs` early-returns `0.0` when `extends_name` is `None` *before* it can reach the `extends_expr` dynamic dispatch — i.e. the base ctor would stop running (wall 38). The harm cited (duplicate own fields / unrecognized inherited accessors) does not materialize: the capture-union (`lookup_class_captures("default")`) and inherited-field-dedup (`lookup_class_field_names("default")`) lookups simply no-op on the unresolved `"default"` key — they don't duplicate, they skip dedup, and the subclass only declares its own captures. The genuine dynamic-parent field-*inheritance* gap is tracked separately as wall 45.

Verified wall-38/42 repro still green after the changes: `super.getRequestHandler()` resolves to a function and the inherited handler returns `HR:1,2,3` (base ctor ran + super.method dispatched).
